package standard

import (
	"github.com/MagicalTux/goro/core"
	"github.com/MagicalTux/goro/core/phpctx"
	"github.com/MagicalTux/goro/core/phpobj"
	"github.com/MagicalTux/goro/core/phpv"
)

// WARNING: This file is auto-generated. DO NOT EDIT

func init() {
	phpctx.RegisterExt(&phpctx.Ext{
		Name:    "standard",
		Version: core.VERSION,
		Classes: []*phpobj.ZClass{
			DirectoryClass,
			RoundingModeEnum,
			PhpUserFilterClass,
		},
		// Note: ExtFunctionArg is currently unused
		Functions: map[string]*phpctx.ExtFunction{
			"abs":                        {Func: mathAbs, Args: []*phpctx.ExtFunctionArg{}},
			"acos":                       {Func: mathAcos, Args: []*phpctx.ExtFunctionArg{}},
			"acosh":                      {Func: mathACosh, Args: []*phpctx.ExtFunctionArg{}},
			"addcslashes":                {Func: fncStrAddCSlashes, Args: []*phpctx.ExtFunctionArg{}},
			"addslashes":                 {Func: fncStrAddSlashes, Args: []*phpctx.ExtFunctionArg{}},
			"array_all":                  {Func: fncArrayAll, Args: []*phpctx.ExtFunctionArg{}},
			"array_any":                  {Func: fncArrayAny, Args: []*phpctx.ExtFunctionArg{}},
			"array_change_key_case":      {Func: fncArrayChangeKeyCase, Args: []*phpctx.ExtFunctionArg{}},
			"array_chunk":                {Func: fncArrayChunk, Args: []*phpctx.ExtFunctionArg{}},
			"array_column":               {Func: fncArrayColumn, Args: []*phpctx.ExtFunctionArg{}},
			"array_combine":              {Func: fncArrayCombine, Args: []*phpctx.ExtFunctionArg{}},
			"array_count_values":         {Func: fncArrayCountValues, Args: []*phpctx.ExtFunctionArg{}},
			"array_diff":                 {Func: fncArrayDiff, Args: []*phpctx.ExtFunctionArg{}},
			"array_diff_assoc":           {Func: fncArrayDiffAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_diff_key":             {Func: fncArrayDiffKey, Args: []*phpctx.ExtFunctionArg{}},
			"array_diff_uassoc":          {Func: fncArrayDiffUAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_diff_ukey":            {Func: fncArrayDiffUKey, Args: []*phpctx.ExtFunctionArg{}},
			"array_fill":                 {Func: fncArrayFill, Args: []*phpctx.ExtFunctionArg{}},
			"array_find":                 {Func: fncArrayFind, Args: []*phpctx.ExtFunctionArg{}},
			"array_find_key":             {Func: fncArrayFindKey, Args: []*phpctx.ExtFunctionArg{}},
			"array_fill_keys":            {Func: fncArrayFillKeys, Args: []*phpctx.ExtFunctionArg{}},
			"array_filter":               {Func: fncArrayFilter, Args: []*phpctx.ExtFunctionArg{}},
			"array_first":                {Func: fncArrayFirst, Args: []*phpctx.ExtFunctionArg{}},
			"array_flip":                 {Func: fncArrayFlip, Args: []*phpctx.ExtFunctionArg{}},
			"array_is_list":              {Func: fncArrayIsList, Args: []*phpctx.ExtFunctionArg{}},
			"array_intersect":            {Func: fncArrayIntersect, Args: []*phpctx.ExtFunctionArg{}},
			"array_intersect_assoc":      {Func: fncArrayIntersectAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_intersect_key":        {Func: fncArrayIntersectKey, Args: []*phpctx.ExtFunctionArg{}},
			"array_intersect_uassoc":     {Func: fncArrayIntersectUAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_intersect_ukey":       {Func: fncArrayIntersectUKey, Args: []*phpctx.ExtFunctionArg{}},
			"array_key_exists":           {Func: fncArrayKeyExists, Args: []*phpctx.ExtFunctionArg{}},
			"array_key_first":            {Func: fncArrayKeyFirst, Args: []*phpctx.ExtFunctionArg{}},
			"array_key_last":             {Func: fncArrayKeyLast, Args: []*phpctx.ExtFunctionArg{}},
			"array_keys":                 {Func: fncArrayKeys, Args: []*phpctx.ExtFunctionArg{}},
			"array_last":                 {Func: fncArrayLast, Args: []*phpctx.ExtFunctionArg{}},
			"array_map":                  {Func: fncArrayMap, Args: []*phpctx.ExtFunctionArg{}},
			"array_merge":                {Func: fncArrayMerge, Args: []*phpctx.ExtFunctionArg{}},
			"array_merge_recursive":      {Func: fncArrayMergeRecursive, Args: []*phpctx.ExtFunctionArg{}},
			"array_multisort":            {Func: fncArrayMultiSort},
			"array_pad":                  {Func: fncArrayPad, Args: []*phpctx.ExtFunctionArg{}},
			"array_pop":                  {Func: fncArrayPop, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"array_product":              {Func: fncArrayProduct, Args: []*phpctx.ExtFunctionArg{}},
			"array_push":                 {Func: fncArrayPush, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"array_rand":                 {Func: fncArrayRand, Args: []*phpctx.ExtFunctionArg{}},
			"array_reduce":               {Func: fncArrayReduce, Args: []*phpctx.ExtFunctionArg{}},
			"array_replace":              {Func: fncArrayReplace, Args: []*phpctx.ExtFunctionArg{}},
			"array_replace_recursive":    {Func: fncArrayReplaceRecursive, Args: []*phpctx.ExtFunctionArg{}},
			"array_reverse":              {Func: fncArrayReverse, Args: []*phpctx.ExtFunctionArg{}},
			"array_search":               {Func: fncArraySearch, Args: []*phpctx.ExtFunctionArg{}},
			"array_shift":                {Func: fncArrayShift, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"array_slice":                {Func: fncArraySlice, Args: []*phpctx.ExtFunctionArg{}},
			"array_splice":               {Func: fncArraySplice, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "offset"}, {ArgName: "length", Optional: true}, {ArgName: "replacement", Optional: true}}},
			"array_sum":                  {Func: fncArraySum, Args: []*phpctx.ExtFunctionArg{}},
			"array_udiff":                {Func: fncArrayUDiff, Args: []*phpctx.ExtFunctionArg{}},
			"array_udiff_assoc":          {Func: fncArrayUDiffAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_udiff_uassoc":         {Func: fncArrayUDiffUAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_uintersect":           {Func: fncArrayUIntersect, Args: []*phpctx.ExtFunctionArg{}},
			"array_uintersect_assoc":     {Func: fncArrayUIntersectAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_uintersect_uassoc":    {Func: fncArrayUIntersectUAssoc, Args: []*phpctx.ExtFunctionArg{}},
			"array_unique":               {Func: fncArrayUnique, Args: []*phpctx.ExtFunctionArg{{ArgName: "array"}, {ArgName: "flags", Optional: true}}},
			"array_unshift":              {Func: fncArrayUnshift, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"array_values":               {Func: fncArrayValues, Args: []*phpctx.ExtFunctionArg{}},
			"array_walk":                 {Func: fncArrayWalk, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "callback"}, {ArgName: "arg", Optional: true}}},
			"array_walk_recursive":       {Func: fncArrayWalkRecursive, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "callback"}, {ArgName: "arg", Optional: true}}},
			"arsort":                     {Func: fncArrayARSort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "flags", Optional: true}}},
			"asin":                       {Func: mathAsin, Args: []*phpctx.ExtFunctionArg{}},
			"asinh":                      {Func: mathAsinh, Args: []*phpctx.ExtFunctionArg{}},
			"asort":                      {Func: fncArrayASort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "flags", Optional: true}}},
			"assert":                     {Func: fncAssert, Args: []*phpctx.ExtFunctionArg{}},
			"assert_options":              {Func: fncAssertOptions, Args: []*phpctx.ExtFunctionArg{}},
			"atan":                       {Func: mathAtan, Args: []*phpctx.ExtFunctionArg{}},
			"atan2":                      {Func: mathAtan2, Args: []*phpctx.ExtFunctionArg{}},
			"atanh":                      {Func: mathAtanh, Args: []*phpctx.ExtFunctionArg{}},
			"base64_decode":              {Func: fncBase64Decode, Args: []*phpctx.ExtFunctionArg{}},
			"base64_encode":              {Func: fncBase64Encode, Args: []*phpctx.ExtFunctionArg{}},
			"base_convert":               {Func: mathBaseConvert, Args: []*phpctx.ExtFunctionArg{}},
			"basename":                   {Func: fncBasename, Args: []*phpctx.ExtFunctionArg{}},
			"bin2hex":                    {Func: fncBin2hex, Args: []*phpctx.ExtFunctionArg{}},
			"bindec":                     {Func: mathBinDec, Args: []*phpctx.ExtFunctionArg{}},
			"boolval":                    {Func: fncBoolval, Args: []*phpctx.ExtFunctionArg{}},
			"call_user_func":             {Func: fncCallUserFunc, Args: []*phpctx.ExtFunctionArg{}},
			"call_user_func_array":       {Func: fncCallUserFuncArray, Args: []*phpctx.ExtFunctionArg{}},
			"ceil":                       {Func: mathCeil, Args: []*phpctx.ExtFunctionArg{}},
			"chdir":                      {Func: fncChdir, Args: []*phpctx.ExtFunctionArg{}},
			"chmod":                      {Func: fncChmod, Args: []*phpctx.ExtFunctionArg{}},
			"chop":                       {Func: fncStrRtrim, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"chr":                        {Func: fncChr, Args: []*phpctx.ExtFunctionArg{}},
			"chunk_split":                {Func: fncStrChunkSplit, Args: []*phpctx.ExtFunctionArg{}},
			"class_exists":               {Func: stdClassExists, Args: []*phpctx.ExtFunctionArg{}},
			"closedir":                   {Func: fncClosedir, Args: []*phpctx.ExtFunctionArg{}},
			"compact":                    {Func: fncArrayCompact, Args: []*phpctx.ExtFunctionArg{}},
			"connection_aborted":         {Func: fncConnectionAborted, Args: []*phpctx.ExtFunctionArg{}},
			"connection_status":          {Func: fncConnectionStatus, Args: []*phpctx.ExtFunctionArg{}},
			"constant":                   {Func: constant, Args: []*phpctx.ExtFunctionArg{}},
			"convert_cyr_string":         {Func: fncCyrConvertString, Args: []*phpctx.ExtFunctionArg{}},
			"convert_uudecode":           {Func: convertUuDecode, Args: []*phpctx.ExtFunctionArg{}},
			"convert_uuencode":           {Func: convertUuEncode, Args: []*phpctx.ExtFunctionArg{}},
			"copy":                       {Func: fncCopy, Args: []*phpctx.ExtFunctionArg{}},
			"cos":                        {Func: mathCos, Args: []*phpctx.ExtFunctionArg{}},
			"cosh":                       {Func: mathCosh, Args: []*phpctx.ExtFunctionArg{}},
			"count_chars":                {Func: fncStrCountChars, Args: []*phpctx.ExtFunctionArg{}},
			"clearstatcache":             {Func: fncClearstatcache, Args: []*phpctx.ExtFunctionArg{}},
			"crc32":                      {Func: fncStrCrc32, Args: []*phpctx.ExtFunctionArg{}},
			"crypt":                      {Func: fncCrypt, Args: []*phpctx.ExtFunctionArg{}},
			"current":                    {Func: fncArrayCurrent, Args: []*phpctx.ExtFunctionArg{{ArgName: "array"}}},
			"decbin":                     {Func: mathDecBin, Args: []*phpctx.ExtFunctionArg{}},
			"dechex":                     {Func: mathDecHex, Args: []*phpctx.ExtFunctionArg{}},
			"decoct":                     {Func: mathDecOct, Args: []*phpctx.ExtFunctionArg{}},
			"deg2rad":                    {Func: mathDeg2rad, Args: []*phpctx.ExtFunctionArg{}},
			"die":                        {Func: die, Args: []*phpctx.ExtFunctionArg{{ArgName: "status", Optional: true}}},
			"dir":                        {Func: fncDir, Args: []*phpctx.ExtFunctionArg{}},
			"dirname":                    {Func: fncDirname, Args: []*phpctx.ExtFunctionArg{}},
			"disk_free_space":            {Func: fncDiskFreeSpace, Args: []*phpctx.ExtFunctionArg{}},
			"disk_total_space":           {Func: fncDiskTotalSpace, Args: []*phpctx.ExtFunctionArg{}},
			"diskfreespace":              {Func: fncDiskFreeSpace, Args: []*phpctx.ExtFunctionArg{}},
			"dl":                         {Func: stdFuncDl, Args: []*phpctx.ExtFunctionArg{}},
			"doubleval":                  {Func: fncDoubleval, Args: []*phpctx.ExtFunctionArg{}},
			"each":                       {Func: fncArrayEach, Args: []*phpctx.ExtFunctionArg{}},
			"end":                        {Func: fncArrayEnd, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"enum_exists":                {Func: stdEnumExists, Args: []*phpctx.ExtFunctionArg{}},
			"error_clear_last":           {Func: stdErrorClearLast, Args: []*phpctx.ExtFunctionArg{}},
			"error_get_last":             {Func: stdErrorGetLast, Args: []*phpctx.ExtFunctionArg{}, MinArgs: 0, MaxArgs: 0},
			"escapeshellarg":             {Func: fncEscapeshellarg, Args: []*phpctx.ExtFunctionArg{}},
			"escapeshellcmd":             {Func: fncEscapeshellcmd, Args: []*phpctx.ExtFunctionArg{}},
			"exec":                       {Func: fncExec, Args: []*phpctx.ExtFunctionArg{{ArgName: "command"}, {ArgName: "output", Ref: true, Optional: true}, {ArgName: "result_code", Ref: true, Optional: true}}},
			"eval":                       {Func: stdFuncEval, Args: []*phpctx.ExtFunctionArg{}},
			"exit":                       {Func: exit, Args: []*phpctx.ExtFunctionArg{{ArgName: "status", Optional: true}}},
			"exp":                        {Func: mathExp, Args: []*phpctx.ExtFunctionArg{}},
			"explode":                    {Func: fncStrExplode, Args: []*phpctx.ExtFunctionArg{}},
			"expm1":                      {Func: mathExpm1, Args: []*phpctx.ExtFunctionArg{}},
			"extension_loaded":           {Func: stdFunc, Args: []*phpctx.ExtFunctionArg{}},
			"extract":                    {Func: fncArrayExtract, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", PreferRef: true}, {ArgName: "flags", Optional: true}, {ArgName: "prefix", Optional: true}}},
			"chgrp":                      {Func: fncChgrp, Args: []*phpctx.ExtFunctionArg{}},
			"chown":                      {Func: fncChown, Args: []*phpctx.ExtFunctionArg{}},
			"fclose":                     {Func: fncFileClose, Args: []*phpctx.ExtFunctionArg{}},
			"feof":                       {Func: fncFeof, Args: []*phpctx.ExtFunctionArg{}},
			"fflush":                     {Func: fncFflush, Args: []*phpctx.ExtFunctionArg{}},
			"fgetc":                      {Func: fncFgetc, Args: []*phpctx.ExtFunctionArg{}},
			"fgetcsv":                    {Func: fncFgetcsv, Args: []*phpctx.ExtFunctionArg{{ArgName: "stream"}, {ArgName: "length", Optional: true}, {ArgName: "separator", Optional: true}, {ArgName: "enclosure", Optional: true}, {ArgName: "escape", Optional: true}}},
			"fgets":                      {Func: fncFgets, Args: []*phpctx.ExtFunctionArg{}},
			"file":                       {Func: fncFile, Args: []*phpctx.ExtFunctionArg{}},
			"file_exists":                {Func: fncFileExists, Args: []*phpctx.ExtFunctionArg{}},
			"file_get_contents":          {Func: fncFileGetContents, Args: []*phpctx.ExtFunctionArg{}},
			"file_put_contents":          {Func: fncFilePutContents, Args: []*phpctx.ExtFunctionArg{}},
			"flock":                      {Func: fncFlock, Args: []*phpctx.ExtFunctionArg{{ArgName: "stream"}, {ArgName: "operation"}, {ArgName: "wouldblock", Ref: true, Optional: true}}},
			"fileatime":                  {Func: fncFileatime, Args: []*phpctx.ExtFunctionArg{}},
			"filectime":                  {Func: fncFilectime, Args: []*phpctx.ExtFunctionArg{}},
			"filegroup":                  {Func: fncFilegroup, Args: []*phpctx.ExtFunctionArg{}},
			"fileinode":                  {Func: fncFileinode, Args: []*phpctx.ExtFunctionArg{}},
			"filemtime":                  {Func: fncFilemtime, Args: []*phpctx.ExtFunctionArg{}},
			"fileowner":                  {Func: fncFileowner, Args: []*phpctx.ExtFunctionArg{}},
			"fileperms":                  {Func: fncFileperms, Args: []*phpctx.ExtFunctionArg{}},
			"filesize":                   {Func: fncFilesize, Args: []*phpctx.ExtFunctionArg{}},
			"filetype":                   {Func: fncFiletype, Args: []*phpctx.ExtFunctionArg{}},
			"floatval":                   {Func: fncFloatval, Args: []*phpctx.ExtFunctionArg{}},
			"fdatasync":                  {Func: fncFdatasync, Args: []*phpctx.ExtFunctionArg{}},
			"fdiv":                       {Func: mathFdiv, Args: []*phpctx.ExtFunctionArg{}},
			"floor":                      {Func: mathFloor, Args: []*phpctx.ExtFunctionArg{}},
			"fpow":                       {Func: mathFpow, Args: []*phpctx.ExtFunctionArg{}},
			"flush":                      {Func: fncFlush, Args: []*phpctx.ExtFunctionArg{}},
			"forward_static_call":        {Func: fncForwardStaticCall, Args: []*phpctx.ExtFunctionArg{}},
			"forward_static_call_array":  {Func: fncForwardStaticCallArray, Args: []*phpctx.ExtFunctionArg{}},
			"fmod":                       {Func: mathFmod, Args: []*phpctx.ExtFunctionArg{}},
			"fopen":                      {Func: fncFileOpen, Args: []*phpctx.ExtFunctionArg{}},
			"fprintf":                    {Func: fncFPrintf, Args: []*phpctx.ExtFunctionArg{}},
			"fputcsv":                    {Func: fncFputcsv, Args: []*phpctx.ExtFunctionArg{{ArgName: "stream"}, {ArgName: "fields"}, {ArgName: "separator", Optional: true}, {ArgName: "enclosure", Optional: true}, {ArgName: "escape", Optional: true}}},
			"fstat":                      {Func: fncFstat, Args: []*phpctx.ExtFunctionArg{}},
			"fputs":                      {Func: fncFwrite, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"fread":                      {Func: fncFread, Args: []*phpctx.ExtFunctionArg{}},
			"fseek":                      {Func: fncFseek, Args: []*phpctx.ExtFunctionArg{}},
			"fscanf":                     {Func: fncFscanf, Args: []*phpctx.ExtFunctionArg{{ArgName: "stream"}, {ArgName: "format"}, {ArgName: "vars", Ref: true, Variadic: true, Optional: true}}},
			"fsync":                      {Func: fncFsync, Args: []*phpctx.ExtFunctionArg{}},
			"ftell":                      {Func: fncFtell, Args: []*phpctx.ExtFunctionArg{}},
			"ftruncate":                  {Func: fncFtruncate, Args: []*phpctx.ExtFunctionArg{}},
			"function_exists":            {Func: stdFuncFuncExists, Args: []*phpctx.ExtFunctionArg{}},
			"fwrite":                     {Func: fncFwrite, Args: []*phpctx.ExtFunctionArg{}},
			"get_cfg_var":                {Func: stdFuncGetCfgVar, Args: []*phpctx.ExtFunctionArg{}},
			"get_current_user":           {Func: fncGetCurrentUser, Args: []*phpctx.ExtFunctionArg{}},
			"get_class":                  {Func: stdGetClass, Args: []*phpctx.ExtFunctionArg{}},
			"get_class_methods":          {Func: stdGetClassMethods, Args: []*phpctx.ExtFunctionArg{}},
			"get_class_vars":             {Func: stdGetClassVars, Args: []*phpctx.ExtFunctionArg{}},
			"get_declared_classes":       {Func: stdGetDeclaredClasses, Args: []*phpctx.ExtFunctionArg{}},
			"get_declared_interfaces":   {Func: stdGetDeclaredInterfaces, Args: []*phpctx.ExtFunctionArg{}},
			"get_declared_traits":       {Func: stdGetDeclaredTraits, Args: []*phpctx.ExtFunctionArg{}},
			"get_defined_constants":      {Func: stdGetDefinedConstants, Args: []*phpctx.ExtFunctionArg{}},
			"get_debug_type":             {Func: fncGetDebugType, Args: []*phpctx.ExtFunctionArg{}},
			"get_extension_funcs":        {Func: fncGetExtensionFuncs, Args: []*phpctx.ExtFunctionArg{}},
			"get_html_translation_table": {Func: fncGetHtmlTranslationTable, Args: []*phpctx.ExtFunctionArg{}},
			"get_include_path":           {Func: fncGetIncludePath, Args: []*phpctx.ExtFunctionArg{}},
			"get_included_files":         {Func: fncGetIncludedFiles, Args: []*phpctx.ExtFunctionArg{}},
			"get_required_files":         {Func: fncGetIncludedFiles, Args: []*phpctx.ExtFunctionArg{}},
			"get_magic_quotes_gpc":       {Func: getMagicQuotesGpc, Args: []*phpctx.ExtFunctionArg{}},
			"get_magic_quotes_runtime":   {Func: getMagicQuotesRuntime, Args: []*phpctx.ExtFunctionArg{}},
			"get_mangled_object_vars":    {Func: stdGetMangledObjectVars, Args: []*phpctx.ExtFunctionArg{}},
			"get_object_vars":            {Func: stdGetObjectVars, Args: []*phpctx.ExtFunctionArg{}},
			"get_parent_class":           {Func: stdGetParentClass, Args: []*phpctx.ExtFunctionArg{}},
			"get_resource_id":            {Func: fncGetResourceId, Args: []*phpctx.ExtFunctionArg{}},
			"get_resource_type":          {Func: fncGetResourceType, Args: []*phpctx.ExtFunctionArg{}},
			"get_resources":              {Func: fncGetResources, Args: []*phpctx.ExtFunctionArg{}},
			"getcwd":                     {Func: fncGetcwd, Args: []*phpctx.ExtFunctionArg{}},
			"glob":                       {Func: fncGlob, Args: []*phpctx.ExtFunctionArg{}},
			"getenv":                     {Func: getenv, Args: []*phpctx.ExtFunctionArg{}},
			"gethostname":                {Func: fncGethostname, Args: []*phpctx.ExtFunctionArg{}},
			"getmygid":                   {Func: fncGetmygid, Args: []*phpctx.ExtFunctionArg{}},
			"getmypid":                   {Func: fncGetmypid, Args: []*phpctx.ExtFunctionArg{}},
			"getmyuid":                   {Func: fncGetmyuid, Args: []*phpctx.ExtFunctionArg{}},
			"getrusage":                  {Func: fncGetrusage, Args: []*phpctx.ExtFunctionArg{}},
			"getservbyname":              {Func: fncGetservbyname, Args: []*phpctx.ExtFunctionArg{}},
			"getservbyport":              {Func: fncGetservbyport, Args: []*phpctx.ExtFunctionArg{}},
			"getopt":                     {Func: fncGetOpt, Args: []*phpctx.ExtFunctionArg{}},
			"getlastmod":                 {Func: fncGetlastmod, Args: []*phpctx.ExtFunctionArg{}},
			"getrandmax":                 {Func: mathMtGetRandMax, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"gettype":                    {Func: fncGettype, Args: []*phpctx.ExtFunctionArg{}},
			"header":                     {Func: fncHeader, Args: []*phpctx.ExtFunctionArg{}},
			"header_register_callback":   {Func: fncHeaderRegisterCallback, Args: []*phpctx.ExtFunctionArg{}},
			"header_remove":              {Func: fncHeaderRemove, Args: []*phpctx.ExtFunctionArg{}},
			"headers_list":               {Func: fncHeaderList, Args: []*phpctx.ExtFunctionArg{}},
			"headers_sent":               {Func: fncHeadersSent, Args: []*phpctx.ExtFunctionArg{}},
			"hebrev":                     {Func: fncHebrev, Args: []*phpctx.ExtFunctionArg{}},
			"hebrevc":                    {Func: fncHebrevc, Args: []*phpctx.ExtFunctionArg{}},
			"hex2bin":                    {Func: fncHex2Bin, Args: []*phpctx.ExtFunctionArg{}},
			"hexdec":                     {Func: mathHexDec, Args: []*phpctx.ExtFunctionArg{}},
			"highlight_file":             {Func: fncHighlightFile, Args: []*phpctx.ExtFunctionArg{}},
			"highlight_string":           {Func: fncHighlightString, Args: []*phpctx.ExtFunctionArg{}},
			"hrtime":                     {Func: stdFuncHrTime, Args: []*phpctx.ExtFunctionArg{}},
			"http_build_query":           {Func: fncHttpBuildQuery, Args: []*phpctx.ExtFunctionArg{}},
			"http_response_code":         {Func: fncHttpResponseCode, Args: []*phpctx.ExtFunctionArg{}},
			"htmlspecialchars":           {Func: fncHtmlSpecialChars, Args: []*phpctx.ExtFunctionArg{}},
			"htmlspecialchars_decode":    {Func: fncHtmlSpecialCharsDecode, Args: []*phpctx.ExtFunctionArg{}},
			"htmlentities":               {Func: fncHtmlEntities, Args: []*phpctx.ExtFunctionArg{}},
			"html_entity_decode":         {Func: fncHtmlEntityDecode, Args: []*phpctx.ExtFunctionArg{}},
			"hypot":                      {Func: mathHypot, Args: []*phpctx.ExtFunctionArg{}},
			"ignore_user_abort":          {Func: fncIgnoreUserAbort, Args: []*phpctx.ExtFunctionArg{}},
			"implode":                    {Func: fncStrImplode, Args: []*phpctx.ExtFunctionArg{}},
			"in_array":                   {Func: fncInArray, Args: []*phpctx.ExtFunctionArg{}},
			"inet_ntop":                  {Func: fncInetNtop, Args: []*phpctx.ExtFunctionArg{}},
			"inet_pton":                  {Func: fncInetPton, Args: []*phpctx.ExtFunctionArg{}},
			"ip2long":                    {Func: fncIp2long, Args: []*phpctx.ExtFunctionArg{}},
			"intdiv":                     {Func: mathIntDiv, Args: []*phpctx.ExtFunctionArg{}},
			"interface_exists":           {Func: stdInterfaceExists, Args: []*phpctx.ExtFunctionArg{}},
			"intval":                     {Func: fncIntval, Args: []*phpctx.ExtFunctionArg{}},
			"is_a":                       {Func: stdIsA, Args: []*phpctx.ExtFunctionArg{}},
			"is_array":                   {Func: fncIsArray, Args: []*phpctx.ExtFunctionArg{}},
			"is_bool":                    {Func: fncIsBool, Args: []*phpctx.ExtFunctionArg{}},
			"is_dir":                     {Func: fncIsDir, Args: []*phpctx.ExtFunctionArg{}},
			"is_double":                  {Func: fncIsDouble, Args: []*phpctx.ExtFunctionArg{}},
			"is_executable":              {Func: fncIsExecutable, Args: []*phpctx.ExtFunctionArg{}},
			"is_file":                    {Func: fncIsFile, Args: []*phpctx.ExtFunctionArg{}},
			"is_finite":                  {Func: mathIsFinite, Args: []*phpctx.ExtFunctionArg{}},
			"is_float":                   {Func: fncIsFloat, Args: []*phpctx.ExtFunctionArg{}},
			"is_infinite":                {Func: mathIsInfinite, Args: []*phpctx.ExtFunctionArg{}},
			"is_int":                     {Func: fncIsInt, Args: []*phpctx.ExtFunctionArg{}},
			"is_integer":                 {Func: fncIsInteger, Args: []*phpctx.ExtFunctionArg{}},
			"is_link":                    {Func: fncIsLink, Args: []*phpctx.ExtFunctionArg{}},
			"is_long":                    {Func: fncIsLong, Args: []*phpctx.ExtFunctionArg{}},
			"is_uploaded_file":           {Func: fncIsUploadedFile, Args: []*phpctx.ExtFunctionArg{}},
			"is_nan":                     {Func: mathIsNaN, Args: []*phpctx.ExtFunctionArg{}},
			"is_null":                    {Func: fncIsNull, Args: []*phpctx.ExtFunctionArg{}},
			"is_numeric":                 {Func: fncIsNumeric, Args: []*phpctx.ExtFunctionArg{}},
			"is_object":                  {Func: fncIsObject, Args: []*phpctx.ExtFunctionArg{}},
			"is_readable":                {Func: fncIsReadable, Args: []*phpctx.ExtFunctionArg{}},
			"is_real":                    {Func: fncIsReal, Args: []*phpctx.ExtFunctionArg{}},
			"is_resource":                {Func: fncIsResource, Args: []*phpctx.ExtFunctionArg{}},
			"is_countable":               {Func: fncIsCountable, Args: []*phpctx.ExtFunctionArg{}},
			"is_iterable":                {Func: fncIsIterable, Args: []*phpctx.ExtFunctionArg{}},
			"is_scalar":                  {Func: fncIsScalar, Args: []*phpctx.ExtFunctionArg{}},
			"is_string":                  {Func: fncIsString, Args: []*phpctx.ExtFunctionArg{}},
			"is_subclass_of":             {Func: stdIsSubclassOf, Args: []*phpctx.ExtFunctionArg{}},
			"is_writable":                {Func: fncIsWritable, Args: []*phpctx.ExtFunctionArg{}},
			"is_writeable":               {Func: fncIsWritable, Args: []*phpctx.ExtFunctionArg{}},
			"join":                       {Func: fncStrImplode, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"key":                        {Func: fncArrayKey, Args: []*phpctx.ExtFunctionArg{}},
			"key_exists":                 {Func: fncArrayKeyExists, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"krsort":                     {Func: fncArrayKRSort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "flags", Optional: true}}},
			"ksort":                      {Func: fncArrayKSort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "flags", Optional: true}}},
			"lcfirst":                    {Func: fncStrLcFirst, Args: []*phpctx.ExtFunctionArg{}},
			"levenshtein":                {Func: fncLevenshtein, Args: []*phpctx.ExtFunctionArg{}},
			"link":                       {Func: fncLink, Args: []*phpctx.ExtFunctionArg{}},
			"linkinfo":                   {Func: fncLinkinfo, Args: []*phpctx.ExtFunctionArg{}},
			"lcg_value":                  {Func: fncLcgValue, Args: []*phpctx.ExtFunctionArg{}},
			"localeconv":                 {Func: fncLocaleConv, Args: []*phpctx.ExtFunctionArg{}},
			"long2ip":                    {Func: fncLong2ip, Args: []*phpctx.ExtFunctionArg{}},
			"log":                        {Func: mathLog, Args: []*phpctx.ExtFunctionArg{}},
			"log10":                      {Func: mathLog10, Args: []*phpctx.ExtFunctionArg{}},
			"log1p":                      {Func: mathLog1P, Args: []*phpctx.ExtFunctionArg{}},
			"lstat":                      {Func: fncLstat, Args: []*phpctx.ExtFunctionArg{}},
			"ltrim":                      {Func: fncStrLtrim, Args: []*phpctx.ExtFunctionArg{}},
			"max":                        {Func: mathMax, Args: []*phpctx.ExtFunctionArg{}},
			"memory_get_peak_usage":      {Func: fncMemoryGetPeakUsage, Args: []*phpctx.ExtFunctionArg{}},
			"memory_get_usage":           {Func: fncMemoryGetUsage, Args: []*phpctx.ExtFunctionArg{}},
			"memory_reset_peak_usage":   {Func: fncMemoryResetPeakUsage, Args: []*phpctx.ExtFunctionArg{}},
			"md5":                        {Func: fncStrMd5, Args: []*phpctx.ExtFunctionArg{}},
			"md5_file":                   {Func: fncStrMd5File, Args: []*phpctx.ExtFunctionArg{}},
			"metaphone":                  {Func: fncMetaphone, Args: []*phpctx.ExtFunctionArg{}},
			"method_exists":              {Func: stdFuncMethodExists, Args: []*phpctx.ExtFunctionArg{}},
			"microtime":                  {Func: fncMicrotime, Args: []*phpctx.ExtFunctionArg{}},
			"min":                        {Func: mathMin, Args: []*phpctx.ExtFunctionArg{}},
			"mkdir":                      {Func: fncMkdir, Args: []*phpctx.ExtFunctionArg{}},
			"move_uploaded_file":         {Func: fncMoveUploadedFile, Args: []*phpctx.ExtFunctionArg{}},
			"mktime":                     {Func: fncMkTime, Args: []*phpctx.ExtFunctionArg{}},
			"mt_getrandmax":              {Func: mathMtGetRandMax, Args: []*phpctx.ExtFunctionArg{}},
			"mt_rand":                    {Func: mathMtRand, Args: []*phpctx.ExtFunctionArg{}},
			"mt_srand":                   {Func: mathMtSRand, Args: []*phpctx.ExtFunctionArg{}},
			"natcasesort":                {Func: fncArrayNatCaseSort, Args: []*phpctx.ExtFunctionArg{}},
			"natsort":                    {Func: fncArrayNatSort, Args: []*phpctx.ExtFunctionArg{}},
			"next":                       {Func: fncArrayNext, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"nl2br":                      {Func: fncStrNewLine2Br, Args: []*phpctx.ExtFunctionArg{}},
			"nl_langinfo":                {Func: fncNlLangInfo, Args: []*phpctx.ExtFunctionArg{}},
			"number_format":              {Func: fncStrNumberFormat, Args: []*phpctx.ExtFunctionArg{}},
			"ob_clean":                   {Func: fncObClean, Args: []*phpctx.ExtFunctionArg{}},
			"ob_end_clean":               {Func: fncObEndClean, Args: []*phpctx.ExtFunctionArg{}},
			"ob_end_flush":               {Func: fncObEndFlush, Args: []*phpctx.ExtFunctionArg{}},
			"ob_flush":                   {Func: fncObFlush, Args: []*phpctx.ExtFunctionArg{}},
			"ob_get_clean":               {Func: fncObGetClean, Args: []*phpctx.ExtFunctionArg{}},
			"ob_get_contents":            {Func: fncObGetContents, Args: []*phpctx.ExtFunctionArg{}},
			"ob_get_flush":               {Func: fncObGetFlush, Args: []*phpctx.ExtFunctionArg{}},
			"ob_get_length":              {Func: fncObGetLength, Args: []*phpctx.ExtFunctionArg{}},
			"ob_get_level":               {Func: fncObGetLevel, Args: []*phpctx.ExtFunctionArg{}},
			"ob_get_status":              {Func: fncObGetStatus, Args: []*phpctx.ExtFunctionArg{}},
			"ob_implicit_flush":          {Func: fncObImplicitFlush, Args: []*phpctx.ExtFunctionArg{}},
			"ob_list_handlers":           {Func: fncObListHandlers, Args: []*phpctx.ExtFunctionArg{}},
			"ob_start":                   {Func: fncObStart, Args: []*phpctx.ExtFunctionArg{}},
			"octdec":                     {Func: mathOctDec, Args: []*phpctx.ExtFunctionArg{}},
			"output_add_rewrite_var":     {Func: fncOutputAddRewriteVar, Args: []*phpctx.ExtFunctionArg{}, MinArgs: 2, MaxArgs: 2},
			"opendir":                    {Func: fncOpendir, Args: []*phpctx.ExtFunctionArg{}},
			"ord":                        {Func: fncOrd, Args: []*phpctx.ExtFunctionArg{}},
			"pack":                       {Func: fncPack, Args: []*phpctx.ExtFunctionArg{}},
			"passthru":                   {Func: fncPassthru, Args: []*phpctx.ExtFunctionArg{{ArgName: "command"}, {ArgName: "result_code", Ref: true, Optional: true}}},
			"pclose":                     {Func: fncPclose, Args: []*phpctx.ExtFunctionArg{}},
			"popen":                      {Func: fncPopen, Args: []*phpctx.ExtFunctionArg{}},
			"parse_str":                  {Func: fncStrParseStr, Args: []*phpctx.ExtFunctionArg{{ArgName: "string"}, {ArgName: "result", Ref: true}}},
			"parse_ini_file":             {Func: fncParseIniFile, Args: []*phpctx.ExtFunctionArg{}},
			"parse_ini_string":           {Func: fncParseIniString, Args: []*phpctx.ExtFunctionArg{}},
			"parse_url":                  {Func: fncParseUrl, Args: []*phpctx.ExtFunctionArg{}},
			"password_algos":             {Func: fncPasswordAlgos, Args: []*phpctx.ExtFunctionArg{}},
			"password_get_info":          {Func: fncPasswordGetInfo, Args: []*phpctx.ExtFunctionArg{}},
			"password_hash":              {Func: fncPasswordHash, Args: []*phpctx.ExtFunctionArg{}},
			"password_needs_rehash":      {Func: fncPasswordNeedsRehash, Args: []*phpctx.ExtFunctionArg{}},
			"password_verify":            {Func: fncPasswordVerify, Args: []*phpctx.ExtFunctionArg{}},
			"pathinfo":                   {Func: fncPathinfo, Args: []*phpctx.ExtFunctionArg{}},
			"php_sapi_name":              {Func: stdFuncSapiName, Args: []*phpctx.ExtFunctionArg{}},
			"php_strip_whitespace":       {Func: fncPhpStripWhitespace, Args: []*phpctx.ExtFunctionArg{}},
			"php_uname":                  {Func: fncUname, Args: []*phpctx.ExtFunctionArg{}},
			"phpcredits":                 {Func: fncPhpCredits, Args: []*phpctx.ExtFunctionArg{}},
			"phpinfo":                    {Func: fncPhpinfo, Args: []*phpctx.ExtFunctionArg{}},
			"pi":                         {Func: mathPi, Args: []*phpctx.ExtFunctionArg{}},
			"pos":                        {Func: fncArrayCurrent, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"pow":                        {Func: mathPow, Args: []*phpctx.ExtFunctionArg{}},
			"proc_nice":                  {Func: fncProcNice, Args: []*phpctx.ExtFunctionArg{}},
			"property_exists":            {Func: stdPropertyExists, Args: []*phpctx.ExtFunctionArg{}},
			"prev":                       {Func: fncArrayPrev, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"print_r":                    {Func: fncPrintR, Args: []*phpctx.ExtFunctionArg{}},
			"printf":                     {Func: fncPrintf, Args: []*phpctx.ExtFunctionArg{}},
			"putenv":                     {Func: putenv, Args: []*phpctx.ExtFunctionArg{}},
			"quoted_printable_decode":    {Func: fncQuotedPrintableDecode, Args: []*phpctx.ExtFunctionArg{}},
			"quoted_printable_encode":    {Func: fncQuotedPrintableEncode, Args: []*phpctx.ExtFunctionArg{}},
			"quotemeta":                  {Func: fncStrQuoteMeta, Args: []*phpctx.ExtFunctionArg{}},
			"rad2deg":                    {Func: mathRad2Deg, Args: []*phpctx.ExtFunctionArg{}},
			"rand":                       {Func: mathMtRand, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"random_bytes":               {Func: fncRandomBytes, Args: []*phpctx.ExtFunctionArg{}},
			"random_int":                 {Func: fncRandomInt, Args: []*phpctx.ExtFunctionArg{}},
			"range":                      {Func: fncRange, Args: []*phpctx.ExtFunctionArg{}},
			"rawurldecode":               {Func: fncRawurldecode, Args: []*phpctx.ExtFunctionArg{}},
			"rawurlencode":               {Func: fncRawurlencode, Args: []*phpctx.ExtFunctionArg{}},
			"readdir":                    {Func: fncReaddir, Args: []*phpctx.ExtFunctionArg{}},
			"readfile":                   {Func: fncReadfile, Args: []*phpctx.ExtFunctionArg{}},
			"readlink":                   {Func: fncReadlink, Args: []*phpctx.ExtFunctionArg{}},
			"realpath":                   {Func: fncRealPath, Args: []*phpctx.ExtFunctionArg{}},
			"register_shutdown_function":   {Func: registerShutdownFunction, Args: []*phpctx.ExtFunctionArg{}},
			"register_tick_function":       {Func: fncRegisterTickFunction, Args: []*phpctx.ExtFunctionArg{}},
			"unregister_tick_function":     {Func: fncUnregisterTickFunction, Args: []*phpctx.ExtFunctionArg{}},
			"rename":                     {Func: fncRename, Args: []*phpctx.ExtFunctionArg{}},
			"reset":                      {Func: fncArrayReset, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"rewind":                     {Func: fncRewind, Args: []*phpctx.ExtFunctionArg{}},
			"rewinddir":                  {Func: fncRewinddir, Args: []*phpctx.ExtFunctionArg{}},
			"rmdir":                      {Func: fncRmdir, Args: []*phpctx.ExtFunctionArg{}},
			"round":                      {Func: mathRound, Args: []*phpctx.ExtFunctionArg{{ArgName: "num"}, {ArgName: "precision", Optional: true}, {ArgName: "mode", Optional: true}}},
			"rsort":                      {Func: fncArrayRSort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "flags", Optional: true}}},
			"rtrim":                      {Func: fncStrRtrim, Args: []*phpctx.ExtFunctionArg{}},
			"scandir":                    {Func: fncScanDir, Args: []*phpctx.ExtFunctionArg{}},
			"serialize":                  {Func: fncSerialize, Args: []*phpctx.ExtFunctionArg{}},
			"set_time_limit":             {Func: fncSetTimeLimit, Args: []*phpctx.ExtFunctionArg{}},
			"setlocale":                  {Func: fncSetLocale, Args: []*phpctx.ExtFunctionArg{}},
			"settype":                    {Func: fncSettype, Args: []*phpctx.ExtFunctionArg{{ArgName: "var", Ref: true}}},
			"set_include_path":           {Func: fncSetIncludePath, Args: []*phpctx.ExtFunctionArg{}},
			"sha1":                       {Func: fncStrSha1, Args: []*phpctx.ExtFunctionArg{}},
			"sha1_file":                  {Func: fncStrSha1File, Args: []*phpctx.ExtFunctionArg{}},
			"shell_exec":                 {Func: fncShellExec, Args: []*phpctx.ExtFunctionArg{}},
			"show_source":                {Func: fncHighlightFile, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"shuffle":                    {Func: fncArrayShuffle, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}}},
			"similar_text":               {Func: fncSimilarText, Args: []*phpctx.ExtFunctionArg{{ArgName: "string1"}, {ArgName: "string2"}, {ArgName: "percent", Ref: true, Optional: true}}},
			"sin":                        {Func: mathSin, Args: []*phpctx.ExtFunctionArg{{ArgName: "num"}}},
			"sinh":                       {Func: mathSinh, Args: []*phpctx.ExtFunctionArg{}},
			"sleep":                      {Func: stdFuncSleep, Args: []*phpctx.ExtFunctionArg{}},
			"sort":                       {Func: fncArraySort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "flags", Optional: true}}},
			"soundex":                    {Func: fncSoundex, Args: []*phpctx.ExtFunctionArg{}},
			"sprintf":                    {Func: fncSprintf, Args: []*phpctx.ExtFunctionArg{}},
			"sqrt":                       {Func: mathSqrt, Args: []*phpctx.ExtFunctionArg{}},
			"srand":                      {Func: mathMtSRand, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"sscanf":                     {Func: fncSscanf, Args: []*phpctx.ExtFunctionArg{{ArgName: "string"}, {ArgName: "format"}, {ArgName: "vars", Ref: true, Variadic: true, Optional: true}}},
			"stat":                       {Func: fncStat, Args: []*phpctx.ExtFunctionArg{}},
			"str_contains":               {Func: fncStrContains, Args: []*phpctx.ExtFunctionArg{}},
			"str_decrement":              {Func: fncStrDecrement, Args: []*phpctx.ExtFunctionArg{}},
			"str_ends_with":              {Func: fncStrEndsWith, Args: []*phpctx.ExtFunctionArg{}},
			"str_increment":              {Func: fncStrIncrement, Args: []*phpctx.ExtFunctionArg{}},
			"str_getcsv":                 {Func: fncStrGetCsv, Args: []*phpctx.ExtFunctionArg{}},
			"str_ireplace":               {Func: stdStrIReplace, Args: []*phpctx.ExtFunctionArg{{ArgName: "search"}, {ArgName: "replace"}, {ArgName: "subject"}, {ArgName: "count", Ref: true, Optional: true}}},
			"str_pad":                    {Func: fncStrPad, Args: []*phpctx.ExtFunctionArg{}},
			"str_repeat":                 {Func: fncStrRepeat, Args: []*phpctx.ExtFunctionArg{}},
			"str_replace":                {Func: stdStrReplace, Args: []*phpctx.ExtFunctionArg{{ArgName: "search"}, {ArgName: "replace"}, {ArgName: "subject"}, {ArgName: "count", Ref: true, Optional: true}}},
			"str_rot13":                  {Func: fncStrRot13, Args: []*phpctx.ExtFunctionArg{}, MinArgs: 1, MaxArgs: 1},
			"str_shuffle":                {Func: fncStrShuffle, Args: []*phpctx.ExtFunctionArg{}},
			"str_split":                  {Func: fncStrSplit, Args: []*phpctx.ExtFunctionArg{}},
			"str_starts_with":            {Func: fncStrStartsWith, Args: []*phpctx.ExtFunctionArg{}},
			"str_word_count":             {Func: fncStrWordCount, Args: []*phpctx.ExtFunctionArg{}},
			"strcasecmp":                 {Func: fncStrCaseCmp, Args: []*phpctx.ExtFunctionArg{}},
			"strchr":                     {Func: fncStrStr, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"strcmp":                     {Func: fncStrCmp, Args: []*phpctx.ExtFunctionArg{}},
			"strcoll":                    {Func: fncStrColl, Args: []*phpctx.ExtFunctionArg{}},
			"strcspn":                    {Func: fncStrCspn, Args: []*phpctx.ExtFunctionArg{}},
			"stream_context_create":      {Func: fncStreamContextCreate, Args: []*phpctx.ExtFunctionArg{}},
			"stream_context_get_default": {Func: fncStreamContextGetDefault, Args: []*phpctx.ExtFunctionArg{}},
			"stream_context_get_options": {Func: fncStreamContextGetOptions, Args: []*phpctx.ExtFunctionArg{}},
			"stream_context_set_default": {Func: fncStreamContextGetDefault, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"stream_context_set_option":  {Func: fncStreamContextSetOption, Args: []*phpctx.ExtFunctionArg{}},
			"stream_context_set_params":  {Func: fncStreamContextSetParams, Args: []*phpctx.ExtFunctionArg{}},
			"stream_context_get_params":  {Func: fncStreamContextGetParams, Args: []*phpctx.ExtFunctionArg{}},
			"stream_bucket_new":          {Func: fncStreamBucketNew, Args: []*phpctx.ExtFunctionArg{}},
			"stream_copy_to_stream":      {Func: fncStreamCopyToStream, Args: []*phpctx.ExtFunctionArg{}},
			"stream_filter_append":       {Func: fncStreamFilterAppend, Args: []*phpctx.ExtFunctionArg{}},
			"stream_filter_prepend":      {Func: fncStreamFilterPrepend, Args: []*phpctx.ExtFunctionArg{}},
			"stream_filter_register":     {Func: fncStreamFilterRegister, Args: []*phpctx.ExtFunctionArg{}},
			"stream_filter_remove":       {Func: fncStreamFilterRemove, Args: []*phpctx.ExtFunctionArg{}},
			"stream_get_contents":        {Func: fncStreamGetContents, Args: []*phpctx.ExtFunctionArg{}},
			"stream_get_filters":         {Func: fncStreamGetFilters, Args: []*phpctx.ExtFunctionArg{}},
			"stream_get_line":            {Func: fncStreamGetLine, Args: []*phpctx.ExtFunctionArg{}},
			"stream_get_meta_data":       {Func: fncStreamGetMetaData, Args: []*phpctx.ExtFunctionArg{}},
			"stream_is_local":            {Func: fncStreamIsLocal, Args: []*phpctx.ExtFunctionArg{}},
			"stream_isatty":              {Func: fncStreamIsatty, Args: []*phpctx.ExtFunctionArg{}},
			"stream_wrapper_register":    {Func: fncStreamWrapperRegister, Args: []*phpctx.ExtFunctionArg{}},
			"stream_wrapper_unregister":  {Func: fncStreamWrapperUnregister, Args: []*phpctx.ExtFunctionArg{}},
			"stream_wrapper_restore":     {Func: fncStreamWrapperRestore, Args: []*phpctx.ExtFunctionArg{}},
			"stream_register_wrapper":    {Func: fncStreamWrapperRegister, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"strip_tags":                 {Func: fncStripTags, Args: []*phpctx.ExtFunctionArg{}},
			"stripcslashes":              {Func: fncStripCSlashes, Args: []*phpctx.ExtFunctionArg{}},
			"stripos":                    {Func: fncStrIPos, Args: []*phpctx.ExtFunctionArg{}},
			"stripslashes":               {Func: fncStripSlashes, Args: []*phpctx.ExtFunctionArg{}},
			"stristr":                    {Func: fncStrIStr, Args: []*phpctx.ExtFunctionArg{}},
			"strnatcasecmp":              {Func: fncStrNatCaseCmp, Args: []*phpctx.ExtFunctionArg{}},
			"strnatcmp":                  {Func: fncStrNatCmp, Args: []*phpctx.ExtFunctionArg{}},
			"strncasecmp":                {Func: fncStrNCaseCmp, Args: []*phpctx.ExtFunctionArg{}},
			"strncmp":                    {Func: fncStrNCmp, Args: []*phpctx.ExtFunctionArg{}},
			"strpbrk":                    {Func: fncStrPbrk, Args: []*phpctx.ExtFunctionArg{}},
			"strpos":                     {Func: fncStrPos, Args: []*phpctx.ExtFunctionArg{}},
			"strrchr":                    {Func: fncStrRChr, Args: []*phpctx.ExtFunctionArg{}},
			"strrev":                     {Func: fncStrRev, Args: []*phpctx.ExtFunctionArg{}},
			"strripos":                   {Func: fncStrIRPos, Args: []*phpctx.ExtFunctionArg{}},
			"strrpos":                    {Func: fncStrRPos, Args: []*phpctx.ExtFunctionArg{}},
			"strspn":                     {Func: fncStrSpn, Args: []*phpctx.ExtFunctionArg{}},
			"strstr":                     {Func: fncStrStr, Args: []*phpctx.ExtFunctionArg{}},
			"strtok":                     {Func: fncStrtok, Args: []*phpctx.ExtFunctionArg{}},
			"strtolower":                 {Func: fncStrToLower, Args: []*phpctx.ExtFunctionArg{}},
			"strtoupper":                 {Func: fncStrToUpper, Args: []*phpctx.ExtFunctionArg{}},
			"strtr":                      {Func: fncStrTr, Args: []*phpctx.ExtFunctionArg{}},
			"strval":                     {Func: fncStrval, Args: []*phpctx.ExtFunctionArg{}},
			"substr":                     {Func: fncSubstr, Args: []*phpctx.ExtFunctionArg{}},
			"substr_compare":             {Func: fncSubstrCompare, Args: []*phpctx.ExtFunctionArg{}},
			"substr_count":               {Func: fncSubstrCount, Args: []*phpctx.ExtFunctionArg{}},
			"substr_replace":             {Func: fncSubstrReplace, Args: []*phpctx.ExtFunctionArg{}},
			"sys_get_temp_dir":           {Func: fncSysGetTempDir, Args: []*phpctx.ExtFunctionArg{}},
			"sys_getloadavg":             {Func: fncSysGetloadavg, Args: []*phpctx.ExtFunctionArg{}},
			"symlink":                    {Func: fncSymlink, Args: []*phpctx.ExtFunctionArg{}},
			"system":                     {Func: fncSystem, Args: []*phpctx.ExtFunctionArg{{ArgName: "command"}, {ArgName: "result_code", Ref: true, Optional: true}}},
			"tan":                        {Func: mathTan, Args: []*phpctx.ExtFunctionArg{}},
			"tanh":                       {Func: mathTanh, Args: []*phpctx.ExtFunctionArg{}},
			"tempnam":                    {Func: fncTempnam, Args: []*phpctx.ExtFunctionArg{}},
			"tmpfile":                    {Func: fncTmpfile, Args: []*phpctx.ExtFunctionArg{}},
			"time":                       {Func: fncTime, Args: []*phpctx.ExtFunctionArg{}},
			"time_nanosleep":             {Func: fncTimeNanosleep, Args: []*phpctx.ExtFunctionArg{}},
			"time_sleep_until":           {Func: fncTimeSleepUntil, Args: []*phpctx.ExtFunctionArg{}},
			"touch":                      {Func: fncTouch, Args: []*phpctx.ExtFunctionArg{}},
			"trait_exists":               {Func: stdTraitExists, Args: []*phpctx.ExtFunctionArg{}},
			"trim":                       {Func: fncStrTrim, Args: []*phpctx.ExtFunctionArg{}},
			"uasort":                     {Func: fncArrayUASort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "callback"}}},
			"ucfirst":                    {Func: fncUcFirst, Args: []*phpctx.ExtFunctionArg{}},
			"ucwords":                    {Func: fncUcWords, Args: []*phpctx.ExtFunctionArg{}},
			"uksort":                     {Func: fncArrayUKSort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "callback"}}},
			"uniqid":                     {Func: fncUniqId, Args: []*phpctx.ExtFunctionArg{}},
			"umask":                      {Func: fncUmask, Args: []*phpctx.ExtFunctionArg{}},
			"unlink":                     {Func: fncUnlink, Args: []*phpctx.ExtFunctionArg{}},
			"unpack":                     {Func: fncUnpack, Args: []*phpctx.ExtFunctionArg{}},
			"unserialize":                {Func: fncUnserialize, Args: []*phpctx.ExtFunctionArg{}},
			"urldecode":                  {Func: fncUrldecode, Args: []*phpctx.ExtFunctionArg{}},
			"urlencode":                  {Func: fncUrlencode, Args: []*phpctx.ExtFunctionArg{}},
			"utf8_decode":                {Func: fncUtf8Decode, Args: []*phpctx.ExtFunctionArg{}},
			"utf8_encode":                {Func: fncUtf8Encode, Args: []*phpctx.ExtFunctionArg{}},
			"usleep":                     {Func: stdFuncUsleep, Args: []*phpctx.ExtFunctionArg{}},
			"usort":                      {Func: fncArrayUSort, Args: []*phpctx.ExtFunctionArg{{ArgName: "array", Ref: true}, {ArgName: "callback"}}},
			"var_dump":                   {Func: stdFuncVarDump, Args: []*phpctx.ExtFunctionArg{}},
			"version_compare":            {Func: fncVersionCompare, Args: []*phpctx.ExtFunctionArg{}},
			"var_export":                 {Func: stdFuncVarExport, Args: []*phpctx.ExtFunctionArg{}},
			"vfprintf":                   {Func: fncVFPrintf, Args: []*phpctx.ExtFunctionArg{}},
			"vprintf":                    {Func: fncVPrintf, Args: []*phpctx.ExtFunctionArg{}},
			"vsprintf":                   {Func: fncVSprintf, Args: []*phpctx.ExtFunctionArg{}},
			"wordwrap":                   {Func: fncWordWrap, Args: []*phpctx.ExtFunctionArg{}},
			"gethostbyname":              {Func: fncGethostbyname, Args: []*phpctx.ExtFunctionArg{}},
			"gethostbyaddr":              {Func: fncGethostbyaddr, Args: []*phpctx.ExtFunctionArg{}},
			"gethostbynamel":             {Func: fncGethostbynamel, Args: []*phpctx.ExtFunctionArg{}},
			"openlog":                    {Func: fncOpenlog, Args: []*phpctx.ExtFunctionArg{}},
			"closelog":                   {Func: fncCloselog, Args: []*phpctx.ExtFunctionArg{}},
			"syslog":                     {Func: fncSyslog, Args: []*phpctx.ExtFunctionArg{}},
			"getprotobyname":             {Func: fncGetprotobyname, Args: []*phpctx.ExtFunctionArg{}},
			"getprotobynumber":           {Func: fncGetprotobynumber, Args: []*phpctx.ExtFunctionArg{}},
			"checkdnsrr":                 {Func: fncCheckdnsrr, Args: []*phpctx.ExtFunctionArg{}},
			"dns_check_record":           {Func: fncCheckdnsrr, Args: []*phpctx.ExtFunctionArg{}},
			"dns_get_record":             {Func: fncDnsGetRecord, Args: []*phpctx.ExtFunctionArg{}},
			"getmxrr":                    {Func: fncGetmxrr, Args: []*phpctx.ExtFunctionArg{}},
			"fsockopen":                  {Func: fncFsockopen, Args: []*phpctx.ExtFunctionArg{}},
			"setcookie":                  {Func: fncSetcookie, Args: []*phpctx.ExtFunctionArg{}},
			"setrawcookie":               {Func: fncSetrawcookie, Args: []*phpctx.ExtFunctionArg{}},
			"net_get_interfaces":         {Func: fncNetGetInterfaces, Args: []*phpctx.ExtFunctionArg{}},
			"stream_get_transports":      {Func: fncStreamGetTransports, Args: []*phpctx.ExtFunctionArg{}},
			"stream_get_wrappers":        {Func: fncStreamGetWrappers, Args: []*phpctx.ExtFunctionArg{}},
			"stream_set_blocking":        {Func: fncStreamSetBlocking, Args: []*phpctx.ExtFunctionArg{}},
			"socket_set_blocking":        {Func: fncStreamSetBlocking, Args: []*phpctx.ExtFunctionArg{}},
			"stream_set_timeout":         {Func: fncStreamSetTimeout, Args: []*phpctx.ExtFunctionArg{}},
			"socket_set_timeout":         {Func: fncStreamSetTimeout, Args: []*phpctx.ExtFunctionArg{}},
			"stream_set_write_buffer":    {Func: fncStreamSetWriteBuffer, Args: []*phpctx.ExtFunctionArg{}},
			"set_file_buffer":            {Func: fncStreamSetWriteBuffer, Args: []*phpctx.ExtFunctionArg{}},
			"stream_set_read_buffer":     {Func: fncStreamSetReadBuffer, Args: []*phpctx.ExtFunctionArg{}},
			"stream_set_chunk_size":      {Func: fncStreamSetChunkSize, Args: []*phpctx.ExtFunctionArg{}},
			"socket_get_status":          {Func: fncStreamGetMetaData, Args: []*phpctx.ExtFunctionArg{}},
			"stream_select":              {Func: fncStreamSelect, Args: []*phpctx.ExtFunctionArg{}},
			"stream_resolve_include_path": {Func: fncStreamResolveIncludePath, Args: []*phpctx.ExtFunctionArg{}},
			"fpassthru":                  {Func: fncFpassthru, Args: []*phpctx.ExtFunctionArg{}},
		},
		Constants: map[phpv.ZString]phpv.Val{
			"ARRAY_FILTER_USE_BOTH":                ARRAY_FILTER_USE_BOTH,
			"ARRAY_FILTER_USE_KEY":                 ARRAY_FILTER_USE_KEY,
			"ASSERT_ACTIVE":                        ASSERT_ACTIVE,
			"ASSERT_WARNING":                       ASSERT_WARNING,
			"ASSERT_BAIL":                          ASSERT_BAIL,
			"ASSERT_EXCEPTION":                     ASSERT_EXCEPTION,
			"ASSERT_CALLBACK":                      ASSERT_CALLBACK,
			"CONNECTION_NORMAL":                    phpv.ZInt(0),
			"CONNECTION_ABORTED":                   phpv.ZInt(1),
			"CONNECTION_TIMEOUT":                   phpv.ZInt(2),
			"INFO_GENERAL":                         phpv.ZInt(1),
			"INFO_CREDITS":                         phpv.ZInt(2),
			"INFO_CONFIGURATION":                   phpv.ZInt(4),
			"INFO_MODULES":                         phpv.ZInt(8),
			"INFO_ENVIRONMENT":                     phpv.ZInt(16),
			"INFO_VARIABLES":                       phpv.ZInt(32),
			"INFO_LICENSE":                         phpv.ZInt(64),
			"INFO_ALL":                             phpv.ZInt(-1),
			"CREDITS_GROUP":                        phpv.ZInt(1),
			"CREDITS_GENERAL":                      phpv.ZInt(2),
			"CREDITS_SAPI":                         phpv.ZInt(4),
			"CREDITS_MODULES":                      phpv.ZInt(8),
			"CREDITS_DOCS":                         phpv.ZInt(16),
			"CREDITS_FULLPAGE":                     phpv.ZInt(32),
			"CREDITS_QA":                           phpv.ZInt(64),
			"CREDITS_ALL":                          phpv.ZInt(-1),
			"CASE_LOWER":                           CASE_LOWER,
			"CASE_UPPER":                           CASE_UPPER,
			"ENT_COMPAT":                           ENT_COMPAT,
			"ENT_DISALLOWED":                       ENT_DISALLOWED,
			"ENT_HTML401":                          ENT_HTML401,
			"ENT_HTML5":                            ENT_HTML5,
			"ENT_HTML_DOC_HTML401":                 ENT_HTML_DOC_HTML401,
			"ENT_HTML_DOC_HTML5":                   ENT_HTML_DOC_HTML5,
			"ENT_HTML_DOC_TYPE_MASK":               ENT_HTML_DOC_TYPE_MASK,
			"ENT_HTML_DOC_XHTML":                   ENT_HTML_DOC_XHTML,
			"ENT_HTML_DOC_XML1":                    ENT_HTML_DOC_XML1,
			"ENT_HTML_IGNORE_ERRORS":               ENT_HTML_IGNORE_ERRORS,
			"ENT_HTML_QUOTE_DOUBLE":                ENT_HTML_QUOTE_DOUBLE,
			"ENT_HTML_QUOTE_NONE":                  ENT_HTML_QUOTE_NONE,
			"ENT_HTML_QUOTE_SINGLE":                ENT_HTML_QUOTE_SINGLE,
			"ENT_HTML_SUBSTITUTE_DISALLOWED_CHARS": ENT_HTML_SUBSTITUTE_DISALLOWED_CHARS,
			"ENT_HTML_SUBSTITUTE_ERRORS":           ENT_HTML_SUBSTITUTE_ERRORS,
			"ENT_IGNORE":                           ENT_IGNORE,
			"ENT_NOQUOTES":                         ENT_NOQUOTES,
			"ENT_QUOTES":                           ENT_QUOTES,
			"ENT_SUBSTITUTE":                       ENT_SUBSTITUTE,
			"ENT_XHTML":                            ENT_XHTML,
			"ENT_XML1":                             ENT_XML1,
			"EXTR_IF_EXISTS":                       EXTR_IF_EXISTS,
			"EXTR_OVERWRITE":                       EXTR_OVERWRITE,
			"EXTR_PREFIX_ALL":                      EXTR_PREFIX_ALL,
			"EXTR_PREFIX_IF_EXISTS":                EXTR_PREFIX_IF_EXISTS,
			"EXTR_PREFIX_INVALID":                  EXTR_PREFIX_INVALID,
			"EXTR_PREFIX_SAME":                     EXTR_PREFIX_SAME,
			"EXTR_REFS":                            EXTR_REFS,
			"EXTR_SKIP":                            EXTR_SKIP,
			"GLOB_BRACE":                           GLOB_BRACE,
			"GLOB_ERR":                             GLOB_ERR,
			"GLOB_MARK":                            GLOB_MARK,
			"GLOB_NOCHECK":                         GLOB_NOCHECK,
			"GLOB_NOESCAPE":                        GLOB_NOESCAPE,
			"GLOB_NOSORT":                          GLOB_NOSORT,
			"GLOB_ONLYDIR":                         GLOB_ONLYDIR,
			"FILE_APPEND":                          FILE_APPEND,
			"FILE_BINARY":                          FILE_BINARY,
			"FILE_IGNORE_NEW_LINES":                FILE_IGNORE_NEW_LINES,
			"FILE_NO_DEFAULT_CONTEXT":              FILE_NO_DEFAULT_CONTEXT,
			"FILE_SKIP_EMPTY_LINES":                FILE_SKIP_EMPTY_LINES,
			"FILE_TEXT":                             FILE_TEXT,
			"FILE_USE_INCLUDE_PATH":                FILE_USE_INCLUDE_PATH,
			"HTML_ENTITIES":                        HTML_ENTITIES,
			"HTML_SPECIALCHARS":                    HTML_SPECIALCHARS,
			"INF":                                  INF,
			"INI_USER":                             phpv.ZInt(1),
			"INI_PERDIR":                           phpv.ZInt(2),
			"INI_SYSTEM":                           phpv.ZInt(4),
			"INI_ALL":                              phpv.ZInt(7),
			"INI_SCANNER_NORMAL":                   INI_SCANNER_NORMAL,
			"INI_SCANNER_RAW":                      INI_SCANNER_RAW,
			"INI_SCANNER_TYPED":                    INI_SCANNER_TYPED,
			"LOCK_EX":                              LOCK_EX,
			"LOCK_NB":                              LOCK_NB,
			"LOCK_SH":                              LOCK_SH,
			"LOCK_UN":                              LOCK_UN,
			"PASSWORD_BCRYPT":                      phpv.ZStr("2y"),
			"PASSWORD_BCRYPT_DEFAULT_COST":         phpv.ZInt(PASSWORD_BCRYPT_DEFAULT_COST),
			"PASSWORD_DEFAULT":                     phpv.ZStr("2y"),
			"M_1_PI":                               M_1_PI,
			"M_2_PI":                               M_2_PI,
			"M_2_SQRTPI":                           M_2_SQRTPI,
			"M_E":                                  M_E,
			"M_EULER":                              M_EULER,
			"M_LN10":                               M_LN10,
			"M_LN2":                                M_LN2,
			"M_LNPI":                               M_LNPI,
			"M_LOG10E":                             M_LOG10E,
			"M_LOG2E":                              M_LOG2E,
			"M_PHI":                                M_PHI,
			"M_PI":                                 M_PI,
			"M_PI_2":                               M_PI_2,
			"M_PI_4":                               M_PI_4,
			"M_SQRT1_2":                            M_SQRT1_2,
			"M_SQRT2":                              M_SQRT2,
			"M_SQRT3":                              M_SQRT3,
			"M_SQRTPI":                             M_SQRTPI,
			"NAN":                                  NAN,
			"PHP_ROUND_HALF_DOWN":                  PHP_ROUND_HALF_DOWN,
			"PHP_ROUND_HALF_EVEN":                  PHP_ROUND_HALF_EVEN,
			"PHP_ROUND_HALF_ODD":                   PHP_ROUND_HALF_ODD,
			"PHP_ROUND_HALF_UP":                    PHP_ROUND_HALF_UP,
			"SEEK_SET":                             phpv.ZInt(0),
			"SEEK_CUR":                             phpv.ZInt(1),
			"SEEK_END":                             phpv.ZInt(2),
			"SCANDIR_SORT_ASCENDING":               SCANDIR_SORT_ASCENDING,
			"SCANDIR_SORT_DESCENDING":              SCANDIR_SORT_DESCENDING,
			"SCANDIR_SORT_NONE":                    SCANDIR_SORT_NONE,
			"SORT_ASC":                             SORT_ASC,
			"SORT_DESC":                            SORT_DESC,
			"SORT_FLAG_CASE":                       SORT_FLAG_CASE,
			"SORT_LOCALE_STRING":                   SORT_LOCALE_STRING,
			"SORT_NATURAL":                         SORT_NATURAL,
			"SORT_NUMERIC":                         SORT_NUMERIC,
			"SORT_REGULAR":                         SORT_REGULAR,
			"SORT_STRING":                          SORT_STRING,
			"PATHINFO_ALL":                         PATHINFO_ALL,
			"PATHINFO_BASENAME":                    PATHINFO_BASENAME,
			"PATHINFO_DIRNAME":                     PATHINFO_DIRNAME,
			"PATHINFO_EXTENSION":                   PATHINFO_EXTENSION,
			"PATHINFO_FILENAME":                    PATHINFO_FILENAME,
			"PHP_QUERY_RFC1738":                    PHP_QUERY_RFC1738,
			"PHP_QUERY_RFC3986":                    PHP_QUERY_RFC3986,
			"PHP_URL_FRAGMENT":                     PHP_URL_FRAGMENT,
			"PHP_URL_HOST":                         PHP_URL_HOST,
			"PHP_URL_PASS":                         PHP_URL_PASS,
			"PHP_URL_PATH":                         PHP_URL_PATH,
			"PHP_URL_PORT":                         PHP_URL_PORT,
			"PHP_URL_QUERY":                        PHP_URL_QUERY,
			"PHP_URL_SCHEME":                       PHP_URL_SCHEME,
			"PHP_URL_USER":                         PHP_URL_USER,
			"STR_PAD_BOTH":                         STR_PAD_BOTH,
			"STR_PAD_LEFT":                         STR_PAD_LEFT,
			"STR_PAD_RIGHT":                        STR_PAD_RIGHT,
			"LOG_EMERG": LOG_EMERG, "LOG_ALERT": LOG_ALERT, "LOG_CRIT": LOG_CRIT, "LOG_ERR": LOG_ERR,
			"LOG_WARNING": LOG_WARNING, "LOG_NOTICE": LOG_NOTICE, "LOG_INFO": LOG_INFO, "LOG_DEBUG": LOG_DEBUG,
			"LOG_KERN": LOG_KERN, "LOG_USER": LOG_USER, "LOG_MAIL": LOG_MAIL, "LOG_DAEMON": LOG_DAEMON,
			"LOG_AUTH": LOG_AUTH, "LOG_SYSLOG": LOG_SYSLOG, "LOG_LPR": LOG_LPR, "LOG_NEWS": LOG_NEWS,
			"LOG_UUCP": LOG_UUCP, "LOG_CRON": LOG_CRON, "LOG_AUTHPRIV": LOG_AUTHPRIV,
			"LOG_LOCAL0": LOG_LOCAL0, "LOG_LOCAL1": LOG_LOCAL1, "LOG_LOCAL2": LOG_LOCAL2, "LOG_LOCAL3": LOG_LOCAL3,
			"LOG_LOCAL4": LOG_LOCAL4, "LOG_LOCAL5": LOG_LOCAL5, "LOG_LOCAL6": LOG_LOCAL6, "LOG_LOCAL7": LOG_LOCAL7,
			"LOG_PID": LOG_PID, "LOG_CONS": LOG_CONS, "LOG_ODELAY": LOG_ODELAY, "LOG_NDELAY": LOG_NDELAY,
			"LOG_NOWAIT": LOG_NOWAIT, "LOG_PERROR": LOG_PERROR,
			"DNS_A": DNS_A, "DNS_NS": DNS_NS, "DNS_CNAME": DNS_CNAME, "DNS_SOA": DNS_SOA,
			"DNS_PTR": DNS_PTR, "DNS_HINFO": DNS_HINFO, "DNS_CAA": DNS_CAA, "DNS_MX": DNS_MX,
			"DNS_TXT": DNS_TXT, "DNS_SRV": DNS_SRV, "DNS_NAPTR": DNS_NAPTR, "DNS_AAAA": DNS_AAAA,
			"DNS_ANY": DNS_ANY, "DNS_ALL": DNS_ALL,
			"STREAM_SERVER_BIND": STREAM_SERVER_BIND, "STREAM_SERVER_LISTEN": STREAM_SERVER_LISTEN,
			"STREAM_CLIENT_CONNECT": STREAM_CLIENT_CONNECT,
			"STREAM_FILTER_READ": STREAM_FILTER_READ, "STREAM_FILTER_WRITE": STREAM_FILTER_WRITE,
			"STREAM_FILTER_ALL": STREAM_FILTER_ALL,
			"STREAM_IS_URL": STREAM_IS_URL,
			"STREAM_SHUT_RD": STREAM_SHUT_RD, "STREAM_SHUT_WR": STREAM_SHUT_WR, "STREAM_SHUT_RDWR": STREAM_SHUT_RDWR,
		},
	})
}
