#!/bin/sh

export SHELL='/bin/bash'
export WINDOWID='67108877'
export QT_ACCESSIBILITY='1'
export COLORTERM='truecolor'
export XDG_CONFIG_DIRS='/home/ronald/.config/kdedefaults:/etc/xdg/xdg-plasma:/etc/xdg'
export XDG_SESSION_PATH='/org/freedesktop/DisplayManager/Session1'
export HISTCONTROL='ignoreboth:erasedups'
export GTK_IM_MODULE='ibus'
export LANGUAGE=''
export SSH_AUTH_SOCK='deleted'
export SHELL_SESSION_ID='12fa274e9ece41f3b0e2172f23a52885'
export MEMORY_PRESSURE_WRITE='c29tZSAyMDAwMDAgMjAwMDAwMAA='
export XMODIFIERS='@im=ibus'
export DESKTOP_SESSION='plasma'
export SSH_AGENT_PID='2764'
export GTK_RC_FILES='/etc/gtk/gtkrc:/home/ronald/.gtkrc:/home/ronald/.config/gtkrc'
export XCURSOR_SIZE='24'
export EDITOR='vim'
export GTK_MODULES='gail:atk-bridge'
export XDG_SEAT='seat0'
export PWD='/home/ronald/proj/goro'
export NIX_PROFILES='/nix/var/nix/profiles/default /home/ronald/.nix-profile'
export LOGNAME='ronald'
export XDG_SESSION_DESKTOP='KDE'
export XDG_SESSION_TYPE='x11'
export GPG_AGENT_INFO='/run/user/1000/gnupg/S.gpg-agent:0:1'
export SYSTEMD_EXEC_PID='2969'
export XAUTHORITY='/tmp/xauth_HZddnR'
export GTK2_RC_FILES='/etc/gtk-2.0/gtkrc:/home/ronald/.gtkrc-2.0:/home/ronald/.config/gtkrc-2.0'
export HOME='/home/ronald'
export LANG='en_US.UTF-8'
export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:'
export XDG_CURRENT_DESKTOP='KDE'
export KONSOLE_DBUS_SERVICE=':1.347'
export MEMORY_PRESSURE_WATCH='/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/background.slice/plasma-kglobalaccel.service/memory.pressure'
export NIX_SSL_CERT_FILE='/etc/ssl/certs/ca-certificates.crt'
export KONSOLE_DBUS_SESSION='/Sessions/1'
export PROFILEHOME=''
export XDG_SEAT_PATH='/org/freedesktop/DisplayManager/Seat0'
export INVOCATION_ID='40e76526dc6f41858c67aa60be6cf358'
export QTWEBENGINE_DICTIONARIES_PATH='/usr/share/hunspell-bdic/'
export KONSOLE_VERSION='230805'
export MANAGERPID='2600'
export DOTNET_BUNDLE_EXTRACT_BASE_DIR='/home/ronald/.cache/dotnet_bundle_extract'
export CLUTTER_IM_MODULE='ibus'
export KDE_SESSION_UID='1000'
export LESSCLOSE='/usr/bin/lesspipe %s %s'
export XDG_SESSION_CLASS='user'
export TERM='xterm-256color'
export LESSOPEN='| /usr/bin/lesspipe %s'
export USER='ronald'
export COLORFGBG='15;0'
export KDE_SESSION_VERSION='5'
export PAM_KWALLET5_LOGIN='/run/user/1000/kwallet5.socket'
export DISPLAY=':0'
export SHLVL='2'
export GSM_SKIP_SSH_AGENT_WORKAROUND='true'
export QT_IM_MODULE='ibus'
export XDG_VTNR='2'
export XDG_SESSION_ID='3'
export XDG_RUNTIME_DIR='/run/user/1000'
export DEBUGINFOD_URLS='https://debuginfod.ubuntu.com '
export BUN_INSTALL='/home/ronald/.bun'
export QT_AUTO_SCREEN_SCALE_FACTOR='0'
export JOURNAL_STREAM='8:28322'
export XCURSOR_THEME='breeze_cursors'
export XDG_DATA_DIRS='/usr/share/plasma:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/home/ronald/.nix-profile/share:/nix/var/nix/profiles/default/share'
export KDE_FULL_SESSION='true'
export PATH='/home/ronald/.dotnet/tools:/home/ronald/.luarocks/bin:/home/ronald/.bun/bin:/home/ronald/go/bin:/home/ronald/.local/bin:/home/ronald/opt/pandoc-3.4/bin:/home/ronald/opt/bflat:/home/ronald/opt/go/bin:/home/ronald/opt/FBX2glTF-linux-x86_64:/home/ronald/opt/watchexec:/home/ronald/opt/nvim/bin:/home/ronald/opt/godot:/home/ronald/opt/reader:/home/ronald/opt/zig:/home/ronald/opt:/home/ronald/bin:/home/ronald/.nix-profile/bin:/home/ronald/.local/bin:/home/ronald/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ronald/.dotnet/tools'
export DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus'
export KDE_APPLICATIONS_AS_SCOPE='1'
export OLDPWD='/home/ronald'
export KONSOLE_DBUS_WINDOW='/Windows/1'
export _='./test/run-tests.php'
export SSH_CLIENT='deleted'
export SSH_TTY='deleted'
export SSH_CONNECTION='deleted'
export TEMP='/tmp'
export TEST_PHP_EXECUTABLE='./php-cli'
export SKIP_ONLINE_TESTS='1'
export TEST_PHP_EXECUTABLE_ESCAPED=''\''./php-cli'\'''
export TEST_PHP_CGI_EXECUTABLE=''
export TEST_PHP_CGI_EXECUTABLE_ESCAPED=''\'''\'''
export TEST_PHPDBG_EXECUTABLE=''
export TEST_PHPDBG_EXECUTABLE_ESCAPED=''\'''\'''
export REDIRECT_STATUS='1'
export QUERY_STRING=''
export PATH_TRANSLATED='/home/ronald/proj/goro/test/php-7.2.10/basic/strings/sprintf_basic7.php'
export SCRIPT_FILENAME='/home/ronald/proj/goro/test/php-7.2.10/basic/strings/sprintf_basic7.php'
export REQUEST_METHOD='GET'
export CONTENT_TYPE=''
export CONTENT_LENGTH=''
export TZ=''
export TEST_PHP_EXTRA_ARGS='  -d "output_handler=" -d "open_basedir=" -d "disable_functions=" -d "output_buffering=Off" -d "error_reporting=32767" -d "display_errors=1" -d "display_startup_errors=1" -d "log_errors=0" -d "html_errors=0" -d "track_errors=0" -d "report_memleaks=1" -d "report_zend_debug=0" -d "docref_root=" -d "docref_ext=.html" -d "error_prepend_string=" -d "error_append_string=" -d "auto_prepend_file=" -d "auto_append_file=" -d "ignore_repeated_errors=0" -d "precision=14" -d "serialize_precision=-1" -d "memory_limit=128M" -d "opcache.fast_shutdown=0" -d "opcache.file_update_protection=0" -d "opcache.revalidate_freq=0" -d "opcache.jit_hot_loop=1" -d "opcache.jit_hot_func=1" -d "opcache.jit_hot_return=1" -d "opcache.jit_hot_side_exit=1" -d "opcache.jit_max_root_traces=100000" -d "opcache.jit_max_side_traces=100000" -d "opcache.jit_max_exit_counters=100000" -d "opcache.protect_memory=1" -d "zend.assertions=1" -d "zend.exception_ignore_args=0" -d "zend.exception_string_param_max_len=15" -d "short_open_tag=0"'
export HTTP_COOKIE=''

case "$1" in
"gdb")
    gdb --args './php-cli'    -d "output_handler=" -d "open_basedir=" -d "disable_functions=" -d "output_buffering=Off" -d "error_reporting=32767" -d "display_errors=1" -d "display_startup_errors=1" -d "log_errors=0" -d "html_errors=0" -d "track_errors=0" -d "report_memleaks=1" -d "report_zend_debug=0" -d "docref_root=" -d "docref_ext=.html" -d "error_prepend_string=" -d "error_append_string=" -d "auto_prepend_file=" -d "auto_append_file=" -d "ignore_repeated_errors=0" -d "precision=14" -d "serialize_precision=-1" -d "memory_limit=128M" -d "opcache.fast_shutdown=0" -d "opcache.file_update_protection=0" -d "opcache.revalidate_freq=0" -d "opcache.jit_hot_loop=1" -d "opcache.jit_hot_func=1" -d "opcache.jit_hot_return=1" -d "opcache.jit_hot_side_exit=1" -d "opcache.jit_max_root_traces=100000" -d "opcache.jit_max_side_traces=100000" -d "opcache.jit_max_exit_counters=100000" -d "opcache.protect_memory=1" -d "zend.assertions=1" -d "zend.exception_ignore_args=0" -d "zend.exception_string_param_max_len=15" -d "short_open_tag=0" -f "/home/ronald/proj/goro/test/php-7.2.10/basic/strings/sprintf_basic7.php"  2>&1
    ;;
"lldb")
    lldb -- './php-cli'    -d "output_handler=" -d "open_basedir=" -d "disable_functions=" -d "output_buffering=Off" -d "error_reporting=32767" -d "display_errors=1" -d "display_startup_errors=1" -d "log_errors=0" -d "html_errors=0" -d "track_errors=0" -d "report_memleaks=1" -d "report_zend_debug=0" -d "docref_root=" -d "docref_ext=.html" -d "error_prepend_string=" -d "error_append_string=" -d "auto_prepend_file=" -d "auto_append_file=" -d "ignore_repeated_errors=0" -d "precision=14" -d "serialize_precision=-1" -d "memory_limit=128M" -d "opcache.fast_shutdown=0" -d "opcache.file_update_protection=0" -d "opcache.revalidate_freq=0" -d "opcache.jit_hot_loop=1" -d "opcache.jit_hot_func=1" -d "opcache.jit_hot_return=1" -d "opcache.jit_hot_side_exit=1" -d "opcache.jit_max_root_traces=100000" -d "opcache.jit_max_side_traces=100000" -d "opcache.jit_max_exit_counters=100000" -d "opcache.protect_memory=1" -d "zend.assertions=1" -d "zend.exception_ignore_args=0" -d "zend.exception_string_param_max_len=15" -d "short_open_tag=0" -f "/home/ronald/proj/goro/test/php-7.2.10/basic/strings/sprintf_basic7.php"  2>&1
    ;;
"valgrind")
    USE_ZEND_ALLOC=0 valgrind $2 './php-cli'    -d "output_handler=" -d "open_basedir=" -d "disable_functions=" -d "output_buffering=Off" -d "error_reporting=32767" -d "display_errors=1" -d "display_startup_errors=1" -d "log_errors=0" -d "html_errors=0" -d "track_errors=0" -d "report_memleaks=1" -d "report_zend_debug=0" -d "docref_root=" -d "docref_ext=.html" -d "error_prepend_string=" -d "error_append_string=" -d "auto_prepend_file=" -d "auto_append_file=" -d "ignore_repeated_errors=0" -d "precision=14" -d "serialize_precision=-1" -d "memory_limit=128M" -d "opcache.fast_shutdown=0" -d "opcache.file_update_protection=0" -d "opcache.revalidate_freq=0" -d "opcache.jit_hot_loop=1" -d "opcache.jit_hot_func=1" -d "opcache.jit_hot_return=1" -d "opcache.jit_hot_side_exit=1" -d "opcache.jit_max_root_traces=100000" -d "opcache.jit_max_side_traces=100000" -d "opcache.jit_max_exit_counters=100000" -d "opcache.protect_memory=1" -d "zend.assertions=1" -d "zend.exception_ignore_args=0" -d "zend.exception_string_param_max_len=15" -d "short_open_tag=0" -f "/home/ronald/proj/goro/test/php-7.2.10/basic/strings/sprintf_basic7.php"  2>&1
    ;;
"rr")
    rr record $2 './php-cli'    -d "output_handler=" -d "open_basedir=" -d "disable_functions=" -d "output_buffering=Off" -d "error_reporting=32767" -d "display_errors=1" -d "display_startup_errors=1" -d "log_errors=0" -d "html_errors=0" -d "track_errors=0" -d "report_memleaks=1" -d "report_zend_debug=0" -d "docref_root=" -d "docref_ext=.html" -d "error_prepend_string=" -d "error_append_string=" -d "auto_prepend_file=" -d "auto_append_file=" -d "ignore_repeated_errors=0" -d "precision=14" -d "serialize_precision=-1" -d "memory_limit=128M" -d "opcache.fast_shutdown=0" -d "opcache.file_update_protection=0" -d "opcache.revalidate_freq=0" -d "opcache.jit_hot_loop=1" -d "opcache.jit_hot_func=1" -d "opcache.jit_hot_return=1" -d "opcache.jit_hot_side_exit=1" -d "opcache.jit_max_root_traces=100000" -d "opcache.jit_max_side_traces=100000" -d "opcache.jit_max_exit_counters=100000" -d "opcache.protect_memory=1" -d "zend.assertions=1" -d "zend.exception_ignore_args=0" -d "zend.exception_string_param_max_len=15" -d "short_open_tag=0" -f "/home/ronald/proj/goro/test/php-7.2.10/basic/strings/sprintf_basic7.php"  2>&1
    ;;
*)
    './php-cli'    -d "output_handler=" -d "open_basedir=" -d "disable_functions=" -d "output_buffering=Off" -d "error_reporting=32767" -d "display_errors=1" -d "display_startup_errors=1" -d "log_errors=0" -d "html_errors=0" -d "track_errors=0" -d "report_memleaks=1" -d "report_zend_debug=0" -d "docref_root=" -d "docref_ext=.html" -d "error_prepend_string=" -d "error_append_string=" -d "auto_prepend_file=" -d "auto_append_file=" -d "ignore_repeated_errors=0" -d "precision=14" -d "serialize_precision=-1" -d "memory_limit=128M" -d "opcache.fast_shutdown=0" -d "opcache.file_update_protection=0" -d "opcache.revalidate_freq=0" -d "opcache.jit_hot_loop=1" -d "opcache.jit_hot_func=1" -d "opcache.jit_hot_return=1" -d "opcache.jit_hot_side_exit=1" -d "opcache.jit_max_root_traces=100000" -d "opcache.jit_max_side_traces=100000" -d "opcache.jit_max_exit_counters=100000" -d "opcache.protect_memory=1" -d "zend.assertions=1" -d "zend.exception_ignore_args=0" -d "zend.exception_string_param_max_len=15" -d "short_open_tag=0" -f "/home/ronald/proj/goro/test/php-7.2.10/basic/strings/sprintf_basic7.php"  2>&1
    ;;
esac