package core

import (
	"github.com/MagicalTux/goro/core/compiler"
	"github.com/MagicalTux/goro/core/locale"
	"github.com/MagicalTux/goro/core/phpctx"
	"github.com/MagicalTux/goro/core/phpobj"
	"github.com/MagicalTux/goro/core/phpv"
)

// WARNING: This file is auto-generated. DO NOT EDIT

func init() {
	// Wire up callable resolvers to avoid import cycles
	phpobj.FiberResolveCallable = SpawnCallable
	compiler.PipeResolveCallable = SpawnCallable

	phpctx.RegisterExt(&phpctx.Ext{
		Name:    "Core",
		Version: VERSION,
		Classes: []*phpobj.ZClass{
			phpobj.AllowDynamicPropertiesClass,
			phpobj.ArgumentCountError,
			phpobj.ArithmeticError,
			phpobj.ArrayAccess,
			phpobj.AttributeClass,
			phpobj.AssertionError,
			phpobj.BadFunctionCallException,
			phpobj.BadMethodCallException,
			compiler.Closure,
			phpobj.CompileError,
			phpobj.DeprecatedClass,
			phpobj.DivisionByZeroError,
			phpobj.DomainException,
			phpobj.Error,
			phpobj.ErrorException,
			phpobj.Exception,
			phpobj.Fiber,
			phpobj.FiberError,
			phpobj.Generator,
			phpobj.ClosedGeneratorError,
			phpobj.InvalidArgumentException,
			phpobj.Iterator,
			phpobj.IteratorAggregate,
			phpobj.LengthException,
			phpobj.LogicException,
			phpobj.NoDiscardClass,
			phpobj.OutOfBoundsException,
			phpobj.OutOfRangeException,
			phpobj.OverrideClass,
			phpobj.OverflowException,
			phpobj.ParseError,
			phpobj.RangeException,
			phpobj.RuntimeException,
			phpobj.Serializable,
			phpobj.StdClass,
			phpobj.Throwable,
			phpobj.Traversable,
			phpobj.TypeError,
			phpobj.UnderflowException,
			phpobj.UnexpectedValueException,
			phpobj.UnhandledMatchError,
			phpobj.UnitEnum,
			phpobj.BackedEnum,
			phpobj.ValueError,
			phpobj.IncompleteClass,
		},
		// Note: ExtFunctionArg is currently unused
		Functions: map[string]*phpctx.ExtFunction{
				"assert_options":             {Func: fncAssertOptions, Args: []*phpctx.ExtFunctionArg{}},
			"class_alias":               {Func: fncClassAlias, Args: []*phpctx.ExtFunctionArg{}},
			"clone":                     {Func: fncClone, MinArgs: 1, MaxArgs: 2, Args: []*phpctx.ExtFunctionArg{{ArgName: "object"}, {ArgName: "withProperties", Optional: true}}},
			"count":                     {Func: fncCount, Args: []*phpctx.ExtFunctionArg{}},
			"debug_backtrace":           {Func: fncDebugBacktrace, Args: []*phpctx.ExtFunctionArg{}},
			"debug_print_backtrace":     {Func: fncDebugPrintBacktrace, Args: []*phpctx.ExtFunctionArg{}},
			"debug_zval_dump":           {Func: fncDebugZvalDump, Args: []*phpctx.ExtFunctionArg{}},
			"define":                    {Func: fncDefine, Args: []*phpctx.ExtFunctionArg{}},
			"defined":                   {Func: fncDefined, Args: []*phpctx.ExtFunctionArg{}},
			"echo":                      {Func: stdFuncEcho, Args: []*phpctx.ExtFunctionArg{}},
			"empty":                     {Func: fncEmpty, Args: []*phpctx.ExtFunctionArg{}},
			"error_log":                 {Func: fncErrorLog, Args: []*phpctx.ExtFunctionArg{}},
			"error_reporting":           {Func: fncErrorReporting, Args: []*phpctx.ExtFunctionArg{}},
			"func_get_arg":              {Func: fncFuncGetArg, Args: []*phpctx.ExtFunctionArg{}},
			"func_get_args":             {Func: fncFuncGetArgs, Args: []*phpctx.ExtFunctionArg{}},
			"func_num_args":             {Func: fncFuncNumArgs, Args: []*phpctx.ExtFunctionArg{}},
			"get_called_class":          {Func: fncGetCalledClass, Args: []*phpctx.ExtFunctionArg{}},
			"get_defined_vars":          {Func: fncGetDefinedVars, Args: []*phpctx.ExtFunctionArg{}},
			"gc_collect_cycles":         {Func: stdFuncGcCollectCycles, Args: []*phpctx.ExtFunctionArg{}},
			"gc_disable":                {Func: stdFuncGcDisable, Args: []*phpctx.ExtFunctionArg{}},
			"gc_enable":                 {Func: stdFuncGcEnable, Args: []*phpctx.ExtFunctionArg{}},
			"gc_enabled":                {Func: stdFuncGcEnabled, Args: []*phpctx.ExtFunctionArg{}},
			"gc_mem_caches":             {Func: stdFuncGcMemCaches, Args: []*phpctx.ExtFunctionArg{}},
			"get_debug_type":            {Func: fncGetDebugType, Args: []*phpctx.ExtFunctionArg{}},
			"get_defined_functions":     {Func: fncGetDefinedFunctions, Args: []*phpctx.ExtFunctionArg{}},
			"get_loaded_extensions":     {Func: fncLoadedExtensions, Args: []*phpctx.ExtFunctionArg{}},
			"include":                   {Func: fncInclude, Args: []*phpctx.ExtFunctionArg{}},
			"include_once":              {Func: fncIncludeOnce, Args: []*phpctx.ExtFunctionArg{}},
			"ini_alter":                 {Func: fncIniSet, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"ini_get":                   {Func: fncIniGet, Args: []*phpctx.ExtFunctionArg{}},
			"ini_get_all":               {Func: fncIniGetAll, Args: []*phpctx.ExtFunctionArg{}},
			"ini_parse_quantity":         {Func: fncIniParseQuantity, Args: []*phpctx.ExtFunctionArg{}},
			"ini_restore":               {Func: fncIniRestore, Args: []*phpctx.ExtFunctionArg{}},
			"ini_set":                   {Func: fncIniSet, Args: []*phpctx.ExtFunctionArg{}},
			"is_callable":               {Func: fncIsCallable, Args: []*phpctx.ExtFunctionArg{{ArgName: "value"}, {ArgName: "syntax_only"}, {ArgName: "callable_name", Ref: true, Optional: true}}},
			"phpversion":                {Func: stdFuncPhpVersion, Args: []*phpctx.ExtFunctionArg{}},
			"print":                     {Func: fncPrint, Args: []*phpctx.ExtFunctionArg{}},
			"require":                   {Func: fncRequire, Args: []*phpctx.ExtFunctionArg{}},
			"require_once":              {Func: fncRequireOnce, Args: []*phpctx.ExtFunctionArg{}},
			"restore_error_handler":     {Func: fncRestoreErrorHandler, Args: []*phpctx.ExtFunctionArg{}},
			"restore_exception_handler": {Func: fncRestoreExceptionHandler, Args: []*phpctx.ExtFunctionArg{}},
			"set_error_handler":         {Func: fncSetErrorHandler, Args: []*phpctx.ExtFunctionArg{}},
			"set_exception_handler":     {Func: fncSetExceptionHandler, Args: []*phpctx.ExtFunctionArg{}},
			"sizeof":                    {Func: fncCount, Args: []*phpctx.ExtFunctionArg{}}, // alias
			"spl_autoload":              {Func: fncSplAutoload, Args: []*phpctx.ExtFunctionArg{}},
			"spl_autoload_register":     {Func: fncSplAutoloadRegister, Args: []*phpctx.ExtFunctionArg{}},
			"spl_autoload_unregister":   {Func: fncSplAutoloadUnregister, Args: []*phpctx.ExtFunctionArg{}},
			"strcmp":                    {Func: fncStrcmp, Args: []*phpctx.ExtFunctionArg{}},
			"strlen":                    {Func: fncStrlen, Args: []*phpctx.ExtFunctionArg{}},
			"trigger_error":             {Func: fncTriggerError, Args: []*phpctx.ExtFunctionArg{}},
			"zend_version":              {Func: stdFuncZendVersion, Args: []*phpctx.ExtFunctionArg{}},
		},
		Constants: map[phpv.ZString]phpv.Val{
			"ASSERT_ACTIVE":                  ASSERT_ACTIVE,
			"ASSERT_WARNING":                 ASSERT_WARNING,
			"ASSERT_BAIL":                    ASSERT_BAIL,
			"ASSERT_CALLBACK":               ASSERT_CALLBACK,
			"ASSERT_QUIET_EVAL":              ASSERT_QUIET,
			"ASSERT_EXCEPTION":               ASSERT_EXCEPTION,
			"ABDAY_1":                        locale.ABDAY_1,
			"ABDAY_2":                        locale.ABDAY_2,
			"ABDAY_3":                        locale.ABDAY_3,
			"ABDAY_4":                        locale.ABDAY_4,
			"ABDAY_5":                        locale.ABDAY_5,
			"ABDAY_6":                        locale.ABDAY_6,
			"ABDAY_7":                        locale.ABDAY_7,
			"ABMON_1":                        locale.ABMON_1,
			"ABMON_10":                       locale.ABMON_10,
			"ABMON_11":                       locale.ABMON_11,
			"ABMON_12":                       locale.ABMON_12,
			"ABMON_2":                        locale.ABMON_2,
			"ABMON_3":                        locale.ABMON_3,
			"ABMON_4":                        locale.ABMON_4,
			"ABMON_5":                        locale.ABMON_5,
			"ABMON_6":                        locale.ABMON_6,
			"ABMON_7":                        locale.ABMON_7,
			"ABMON_8":                        locale.ABMON_8,
			"ABMON_9":                        locale.ABMON_9,
			"AM_STR":                         locale.AM_STR,
			"CODESET":                        locale.CODESET,
			"COUNT_NORMAL":                   COUNT_NORMAL,
			"COUNT_RECURSIVE":                COUNT_RECURSIVE,
			"CRNCYSTR":                       locale.CRNCYSTR,
			"DAY_1":                          locale.DAY_1,
			"DAY_2":                          locale.DAY_2,
			"DAY_3":                          locale.DAY_3,
			"DAY_4":                          locale.DAY_4,
			"DAY_5":                          locale.DAY_5,
			"DAY_6":                          locale.DAY_6,
			"DAY_7":                          locale.DAY_7,
			"DEBUG_BACKTRACE_IGNORE_ARGS":    DEBUG_BACKTRACE_IGNORE_ARGS,
			"DEBUG_BACKTRACE_PROVIDE_OBJECT": DEBUG_BACKTRACE_PROVIDE_OBJECT,
			"DEFAULT_INCLUDE_PATH":           DEFAULT_INCLUDE_PATH,
			"DIRECTORY_SEPARATOR":            DIRECTORY_SEPARATOR,
			"D_FMT":                          locale.D_FMT,
			"D_T_FMT":                        locale.D_T_FMT,
			"E_ALL":                          E_ALL,
			"E_COMPILE_ERROR":                E_COMPILE_ERROR,
			"E_COMPILE_WARNING":              E_COMPILE_WARNING,
			"E_CORE_ERROR":                   E_CORE_ERROR,
			"E_CORE_WARNING":                 E_CORE_WARNING,
			"E_DEPRECATED":                   E_DEPRECATED,
			"E_ERROR":                        E_ERROR,
			"E_NOTICE":                       E_NOTICE,
			"E_PARSE":                        E_PARSE,
			"E_RECOVERABLE_ERROR":            E_RECOVERABLE_ERROR,
			"E_STRICT":                       E_STRICT,
			"E_USER_DEPRECATED":              E_USER_DEPRECATED,
			"E_USER_ERROR":                   E_USER_ERROR,
			"E_USER_NOTICE":                  E_USER_NOTICE,
			"E_USER_WARNING":                 E_USER_WARNING,
			"E_WARNING":                      E_WARNING,
			"FALSE":                          FALSE,
			"LC_ALL":                         locale.LC_ALL,
			"LC_COLLATE":                     locale.LC_COLLATE,
			"LC_CTYPE":                       locale.LC_CTYPE,
			"LC_MESSAGES":                    locale.LC_MESSAGES,
			"LC_MONETARY":                    locale.LC_MONETARY,
			"LC_NUMERIC":                     locale.LC_NUMERIC,
			"LC_TIME":                        locale.LC_TIME,
			"MON_1":                          locale.MON_1,
			"MON_10":                         locale.MON_10,
			"MON_11":                         locale.MON_11,
			"MON_12":                         locale.MON_12,
			"MON_2":                          locale.MON_2,
			"MON_3":                          locale.MON_3,
			"MON_4":                          locale.MON_4,
			"MON_5":                          locale.MON_5,
			"MON_6":                          locale.MON_6,
			"MON_7":                          locale.MON_7,
			"MON_8":                          locale.MON_8,
			"MON_9":                          locale.MON_9,
			"NOEXPR":                         locale.NOEXPR,
			"NOSTR":                          locale.NOSTR,
			"NULL":                           NULL,
			"PATH_SEPARATOR":                 PATH_SEPARATOR,
			"PHP_EOL":                        PHP_EOL,
			"PHP_EXTRA_VERSION":              PHP_EXTRA_VERSION,
			"PHP_FD_SETSIZE":                 PHP_FD_SETSIZE,
			"PHP_FLOAT_DIG":                  PHP_FLOAT_DIG,
			"PHP_FLOAT_EPSILON":              PHP_FLOAT_EPSILON,
			"PHP_FLOAT_MAX":                  PHP_FLOAT_MAX,
			"PHP_FLOAT_MIN":                  PHP_FLOAT_MIN,
			"PHP_INT_MAX":                    PHP_INT_MAX,
			"PHP_INT_MIN":                    PHP_INT_MIN,
			"PHP_INT_SIZE":                   PHP_INT_SIZE,
			"PHP_MAJOR_VERSION":              PHP_MAJOR_VERSION,
			"PHP_MAXPATHLEN":                 PHP_MAXPATHLEN,
			"PHP_MINOR_VERSION":              PHP_MINOR_VERSION,
			"PHP_OS":                         PHP_OS,
			"PHP_OS_FAMILY":                  PHP_OS_FAMILY,
			"PHP_OUTPUT_HANDLER_CLEAN":       phpctx.PHP_OUTPUT_HANDLER_CLEAN,
			"PHP_OUTPUT_HANDLER_CLEANABLE":   phpctx.PHP_OUTPUT_HANDLER_CLEANABLE,
			"PHP_OUTPUT_HANDLER_CONT":        phpctx.PHP_OUTPUT_HANDLER_CONT,
			"PHP_OUTPUT_HANDLER_DISABLED":    phpctx.PHP_OUTPUT_HANDLER_DISABLED,
			"PHP_OUTPUT_HANDLER_END":         phpctx.PHP_OUTPUT_HANDLER_END,
			"PHP_OUTPUT_HANDLER_FINAL":       phpctx.PHP_OUTPUT_HANDLER_FINAL,
			"PHP_OUTPUT_HANDLER_FLUSH":       phpctx.PHP_OUTPUT_HANDLER_FLUSH,
			"PHP_OUTPUT_HANDLER_FLUSHABLE":   phpctx.PHP_OUTPUT_HANDLER_FLUSHABLE,
			"PHP_OUTPUT_HANDLER_PROCESSED":   phpctx.PHP_OUTPUT_HANDLER_PROCESSED,
			"PHP_OUTPUT_HANDLER_REMOVABLE":   phpctx.PHP_OUTPUT_HANDLER_REMOVABLE,
			"PHP_OUTPUT_HANDLER_START":       phpctx.PHP_OUTPUT_HANDLER_START,
			"PHP_OUTPUT_HANDLER_STARTED":     phpctx.PHP_OUTPUT_HANDLER_STARTED,
			"PHP_OUTPUT_HANDLER_STDFLAGS":    phpctx.PHP_OUTPUT_HANDLER_STDFLAGS,
			"PHP_OUTPUT_HANDLER_WRITE":       phpctx.PHP_OUTPUT_HANDLER_WRITE,
			"PHP_RELEASE_VERSION":            PHP_RELEASE_VERSION,
			"PHP_VERSION":                    PHP_VERSION,
			"PHP_VERSION_ID":                 PHP_VERSION_ID,
			"PHP_ZTS":                        PHP_ZTS,
			"PM_STR":                         locale.PM_STR,
			"RADIXCHAR":                      locale.RADIXCHAR,
			"SEEK_CUR":                       SEEK_CUR,
			"SEEK_END":                       SEEK_END,
			"SEEK_SET":                       SEEK_SET,
			"THOUSEP":                        locale.THOUSEP,
			"TRUE":                           TRUE,
			"T_FMT":                          locale.T_FMT,
			"T_FMT_AMPM":                     locale.T_FMT_AMPM,
			"YESEXPR":                        locale.YESEXPR,
			"YESSTR":                         locale.YESSTR,
			"ZEND_THREAD_SAFE":               ZEND_THREAD_SAFE,
		},
	})
}
