package core

import (
	"github.com/MagicalTux/goro/core/compiler"
	"github.com/MagicalTux/goro/core/phpctx"
	"github.com/MagicalTux/goro/core/phpobj"
	"github.com/MagicalTux/goro/core/phpv"
)

// WARNING: This file is auto-generated. DO NOT EDIT

func init() {
	phpctx.RegisterExt(&phpctx.Ext{
		Name:    "Core",
		Version: VERSION,
		Classes: []phpv.ZClass{
			phpobj.ArrayAccess,
			compiler.Closure,
			phpobj.Exception,
			phpobj.Iterator,
			phpobj.IteratorAggregate,
			phpobj.Serializable,
			phpobj.StdClass,
			phpobj.Throwable,
			phpobj.Traversable,
		},
		Functions: map[string]*phpctx.ExtFunction{
			"count":             {Func: fncCount, Args: []*phpctx.ExtFunctionArg{}},
			"define":            {Func: fncDefine, Args: []*phpctx.ExtFunctionArg{}},
			"defined":           {Func: fncDefined, Args: []*phpctx.ExtFunctionArg{}},
			"echo":              {Func: stdFuncEcho, Args: []*phpctx.ExtFunctionArg{}},
			"empty":             {Func: fncEmpty, Args: []*phpctx.ExtFunctionArg{}},
			"error_reporting":   {Func: fncErrorReporting, Args: []*phpctx.ExtFunctionArg{}},
			"func_get_arg":      {Func: fncFuncGetArg, Args: []*phpctx.ExtFunctionArg{}},
			"func_get_args":     {Func: fncFuncGetArgs, Args: []*phpctx.ExtFunctionArg{}},
			"func_num_args":     {Func: fncFuncNumArgs, Args: []*phpctx.ExtFunctionArg{}},
			"gc_collect_cycles": {Func: stdFuncGcCollectCycles, Args: []*phpctx.ExtFunctionArg{}},
			"gc_disable":        {Func: stdFuncGcDisable, Args: []*phpctx.ExtFunctionArg{}},
			"gc_enable":         {Func: stdFuncGcEnable, Args: []*phpctx.ExtFunctionArg{}},
			"gc_enabled":        {Func: stdFuncGcEnabled, Args: []*phpctx.ExtFunctionArg{}},
			"gc_mem_caches":     {Func: stdFuncGcMemCaches, Args: []*phpctx.ExtFunctionArg{}},
			"include":           {Func: fncInclude, Args: []*phpctx.ExtFunctionArg{}},
			"include_once":      {Func: fncIncludeOnce, Args: []*phpctx.ExtFunctionArg{}},
			"phpversion":        {Func: stdFuncPhpVersion, Args: []*phpctx.ExtFunctionArg{}},
			"print":             {Func: fncPrint, Args: []*phpctx.ExtFunctionArg{}},
			"require":           {Func: fncRequire, Args: []*phpctx.ExtFunctionArg{}},
			"require_once":      {Func: fncRequireOnce, Args: []*phpctx.ExtFunctionArg{}},
			"strcmp":            {Func: fncStrcmp, Args: []*phpctx.ExtFunctionArg{}},
			"strlen":            {Func: fncStrlen, Args: []*phpctx.ExtFunctionArg{}},
			"zend_version":      {Func: stdFuncZendVersion, Args: []*phpctx.ExtFunctionArg{}},
		},
		Constants: map[phpv.ZString]phpv.Val{
			"DEFAULT_INCLUDE_PATH":         DEFAULT_INCLUDE_PATH,
			"DIRECTORY_SEPARATOR":          DIRECTORY_SEPARATOR,
			"E_ALL":                        E_ALL,
			"E_COMPILE_ERROR":              E_COMPILE_ERROR,
			"E_COMPILE_WARNING":            E_COMPILE_WARNING,
			"E_CORE_ERROR":                 E_CORE_ERROR,
			"E_CORE_WARNING":               E_CORE_WARNING,
			"E_DEPRECATED":                 E_DEPRECATED,
			"E_ERROR":                      E_ERROR,
			"E_NOTICE":                     E_NOTICE,
			"E_PARSE":                      E_PARSE,
			"E_RECOVERABLE_ERROR":          E_RECOVERABLE_ERROR,
			"E_STRICT":                     E_STRICT,
			"E_USER_DEPRECATED":            E_USER_DEPRECATED,
			"E_USER_ERROR":                 E_USER_ERROR,
			"E_USER_NOTICE":                E_USER_NOTICE,
			"E_USER_WARNING":               E_USER_WARNING,
			"E_WARNING":                    E_WARNING,
			"FALSE":                        FALSE,
			"NULL":                         NULL,
			"PHP_EOL":                      PHP_EOL,
			"PHP_EXTRA_VERSION":            PHP_EXTRA_VERSION,
			"PHP_FD_SETSIZE":               PHP_FD_SETSIZE,
			"PHP_FLOAT_DIG":                PHP_FLOAT_DIG,
			"PHP_FLOAT_EPSILON":            PHP_FLOAT_EPSILON,
			"PHP_FLOAT_MAX":                PHP_FLOAT_MAX,
			"PHP_FLOAT_MIN":                PHP_FLOAT_MIN,
			"PHP_INT_MAX":                  PHP_INT_MAX,
			"PHP_INT_MIN":                  PHP_INT_MIN,
			"PHP_INT_SIZE":                 PHP_INT_SIZE,
			"PHP_MAJOR_VERSION":            PHP_MAJOR_VERSION,
			"PHP_MAXPATHLEN":               PHP_MAXPATHLEN,
			"PHP_MINOR_VERSION":            PHP_MINOR_VERSION,
			"PHP_OS":                       PHP_OS,
			"PHP_OS_FAMILY":                PHP_OS_FAMILY,
			"PHP_OUTPUT_HANDLER_CLEAN":     phpctx.PHP_OUTPUT_HANDLER_CLEAN,
			"PHP_OUTPUT_HANDLER_CLEANABLE": phpctx.PHP_OUTPUT_HANDLER_CLEANABLE,
			"PHP_OUTPUT_HANDLER_CONT":      phpctx.PHP_OUTPUT_HANDLER_CONT,
			"PHP_OUTPUT_HANDLER_END":       phpctx.PHP_OUTPUT_HANDLER_END,
			"PHP_OUTPUT_HANDLER_FINAL":     phpctx.PHP_OUTPUT_HANDLER_FINAL,
			"PHP_OUTPUT_HANDLER_FLUSH":     phpctx.PHP_OUTPUT_HANDLER_FLUSH,
			"PHP_OUTPUT_HANDLER_FLUSHABLE": phpctx.PHP_OUTPUT_HANDLER_FLUSHABLE,
			"PHP_OUTPUT_HANDLER_REMOVABLE": phpctx.PHP_OUTPUT_HANDLER_REMOVABLE,
			"PHP_OUTPUT_HANDLER_START":     phpctx.PHP_OUTPUT_HANDLER_START,
			"PHP_OUTPUT_HANDLER_STDFLAGS":  phpctx.PHP_OUTPUT_HANDLER_STDFLAGS,
			"PHP_OUTPUT_HANDLER_WRITE":     phpctx.PHP_OUTPUT_HANDLER_WRITE,
			"PHP_RELEASE_VERSION":          PHP_RELEASE_VERSION,
			"PHP_VERSION":                  PHP_VERSION,
			"PHP_VERSION_ID":               PHP_VERSION_ID,
			"PHP_ZTS":                      PHP_ZTS,
			"TRUE":                         TRUE,
			"ZEND_THREAD_SAFE":             ZEND_THREAD_SAFE,
		},
	})
}
